import {
  EncounterTemplate,
  TemperamentConfig,
  UnderstandingSeed,
} from '../core/model';

const peer = {
  role: 'peer',
  relationId: 'friend',
  fallbackLabel: '同伴',
  createIfMissing: { kind: 'friend' as const, label: '同伴', closeness: 5 },
};

const guardian = {
  role: 'guardian',
  relationId: 'parents',
  fallbackLabel: '家人',
};

const partner = {
  role: 'partner',
  relationId: 'partner',
  fallbackLabel: '身边的人',
  createIfMissing: { kind: 'partner' as const, label: '恋人', closeness: 5 },
};

const elder = {
  role: 'elder',
  relationId: 'mentor',
  fallbackLabel: '领路的人',
  createIfMissing: { kind: 'mentor' as const, label: '师傅', closeness: 4 },
};

export const TEMPERAMENTS: TemperamentConfig[] = [
  {
    id: 'quiet',
    name: '沉静',
    description: '你习惯先看、先听，再决定要不要开口。',
    tags: ['quiet-nature'],
    grantMarks: [{ id: 'clarity', intensity: 2 }],
    world: { threads: [{ id: 'learning_mind', domain: 'learning', label: '好学', intensity: 2 }] },
  },
  {
    id: 'warm',
    name: '热络',
    description: '生人靠近时，你很少先把心门关上。',
    tags: ['warm-nature'],
    grantMarks: [{ id: 'presence', intensity: 2 }],
    world: { threads: [{ id: 'social_ease', domain: 'relationship', label: '人缘', intensity: 2 }] },
  },
  {
    id: 'sturdy',
    name: '耐折腾',
    description: '磕碰来得快，你恢复得也快。',
    tags: ['sturdy-nature'],
    grantMarks: [{ id: 'sturdy', intensity: 2 }],
    world: { threads: [{ id: 'body_resilience', domain: 'health', label: '身子骨', intensity: 2 }] },
  },
  {
    id: 'thrifty',
    name: '会过日子',
    description: '很早你就明白，有些东西用完就没有了。',
    tags: ['thrifty-nature'],
    grantMarks: [{ id: 'savings', intensity: 2 }],
    world: { threads: [{ id: 'career_life', domain: 'career', label: '生计', intensity: 1 }] },
  },
];

export const UNDERSTANDING_SEEDS: UnderstandingSeed[] = [
  {
    id: 'truth-costs-protection',
    theme: 'trust',
    anyFragmentTags: ['truth-punished', 'hid-and-safe', 'shared-blame', 'stayed-quiet'],
    initial: '坦白会让我失去保护。',
    revised: '坦白不能保证安全，但我可以决定和谁一起承担。',
    question: '我还不知道，真话到底会不会把人推开。',
  },
  {
    id: 'silence-keeps-place',
    theme: 'trust',
    anyFragmentTags: ['hid-and-safe', 'workplace-hid', 'secret-kept'],
    initial: '把话藏住，位置才还在。',
    revised: '沉默能换来一时安稳，却也会让该在的人离得更远。',
    question: '我不确定自己是在保护别人，还是在保护那个不敢开口的自己。',
  },
  {
    id: 'leaving-is-abandonment',
    theme: 'belonging',
    anyFragmentTags: ['left-home', 'stayed-home', 'reconnected', 'grew-distant'],
    initial: '离开就是把人抛下。',
    revised: '人可以走开，也可以把来处放在心里，再找机会回去。',
    question: '我还说不清，留下是爱，还是害怕外面的空。',
  },
  {
    id: 'staying-is-erasure',
    theme: 'belonging',
    anyFragmentTags: ['stayed-home', 'new-roots', 'left-again'],
    initial: '留下就会被原来的日子慢慢抹掉。',
    revised: '归属不是地点，是我还愿不愿意被谁需要。',
    question: '我不知道自己属于哪条路，只知道两条路都在要我。',
  },
  {
    id: 'worth-is-being-needed',
    theme: 'worth',
    anyFragmentTags: ['sought-praise', 'cared-kin', 'over-needed', 'kept-boundary'],
    initial: '我被需要，才证明自己有用。',
    revised: '被需要不是我的全部价值，我也可以给自己留一条边界。',
    question: '如果没人叫我，我还算不算被这一世需要过？',
  },
  {
    id: 'boundaries-are-selfish',
    theme: 'worth',
    anyFragmentTags: ['kept-boundary', 'over-needed', 'craft-chosen', 'stable-chosen'],
    initial: '给自己留余地，就是对不起等我的人。',
    revised: '拒绝一次，未必是绝情；一直答应，才会把人耗空。',
    question: '我还分不清，拒绝是自私，还是终于把自己也算进了生活。',
  },
];

export const ENCOUNTERS: EncounterTemplate[] = [
  {
    id: 'trust_broken_cup',
    theme: 'trust',
    title: '碎掉的杯子',
    text: '{guardian}问你：是不是你打碎了那只杯子。屋里很静，只等你开口。',
    minAge: 8,
    maxAge: 11,
    years: 4,
    sceneKind: 'childhood',
    weight: 6,
    people: [guardian],
    triggerKind: 'family',
    triggerNote: '家里的规矩先于你的选择到来。',
    choices: [
      {
        id: 'confess',
        text: '承认是自己碰的',
        preview: '{guardian}会记住你说了实话，也可能罚得更重。',
        costKind: 'free',
        fragmentTags: ['truth-punished', 'spoke-up'],
        understandingHint: '真话换来责罚',
        outcomes: [{
          id: 'scolded',
          weight: 1,
          text: '{guardian}没有因为实话就轻放过你。你被罚站，耳朵里全是“下次长记性”。',
          later: '家里对坦白更严了，你开始掂量开口的代价。',
          world: {
            addTags: ['truth-punished'],
            relations: [{ id: 'parents', closenessDelta: -1, strainDelta: 1 }],
            threads: [{ id: 'family_origin', domain: 'family', intensityDelta: 1 }],
          },
          schedule: [{ templateId: 'trust_share_blame', afterYears: 14, windowYears: 10, note: '多年后，同伴的过错会再次把坦白推到你面前' }],
        }],
      },
      {
        id: 'hide',
        text: '说不是自己',
        preview: '眼下能躲过责罚，这件事会变成你和家里之间的刺。',
        costKind: 'free',
        fragmentTags: ['hid-and-safe', 'secret-kept'],
        outcomes: [{
          id: 'escaped',
          weight: 1,
          text: '{guardian}信了，或假装信了。杯子的事过去了，你却把那句假话咽进肚子里。',
          later: '隐瞒成了你更熟的退路。',
          world: {
            addTags: ['hid-and-safe', 'secret-kept'],
            setFacts: { secret: 'kept' },
            relations: [{ id: 'parents', closenessDelta: 1, strainDelta: 1 }],
          },
        }],
      },
      {
        id: 'mute',
        text: '什么也不说',
        preview: '你既不认，也不辩。场面会僵住。',
        costKind: 'free',
        fragmentTags: ['stayed-quiet'],
        outcomes: [{
          id: 'stiff',
          weight: 1,
          text: '谁也没有再问第二句。杯子被扫走了，话却留在空气里。',
          later: '沉默成了你面对质问的第一种姿势。',
          world: {
            addTags: ['stayed-quiet'],
            relations: [{ id: 'parents', strainDelta: 1 }],
          },
        }],
      },
    ],
  },
  {
    id: 'trust_friend_trouble',
    theme: 'trust',
    title: '同伴惹出的祸',
    text: '{peer}把一件不该做的事推到你身边。有人已经在问：当时你在不在场。',
    minAge: 13,
    maxAge: 17,
    years: 4,
    sceneKind: 'studies',
    weight: 5,
    people: [guardian, peer],
    triggerKind: 'chance',
    triggerNote: '少年的交情把你卷进别人的过错里。',
    choices: [
      {
        id: 'cover',
        text: '替{peer}挡过去',
        preview: '交情会更深，你也可能一起挨骂。',
        costKind: 'free',
        fragmentTags: ['hid-and-safe', 'covered-friend'],
        outcomes: [{
          id: 'bonded',
          weight: 1,
          text: '你把话说圆了。{peer}后来只看了你一眼，像把命交给你保管。',
          later: '你们之间多了一件不能说破的事。',
          world: {
            addTags: ['covered-friend'],
            relations: [
              { id: 'friend', kind: 'friend', label: '同伴', closenessDelta: 2 },
              { id: 'parents', strainDelta: 1 },
            ],
          },
        }],
      },
      {
        id: 'tell',
        text: '把经过说给大人听',
        preview: '事情会水落石出，{peer}可能觉得你出卖了人。',
        costKind: 'break-habit',
        support: { anyFragmentTags: ['spoke-up', 'truth-punished'], ifUnsupported: 'cost-break' },
        supportReason: '你曾经因为开口受过罚，这次再说实话，需要 1 人生点去突破。',
        fragmentTags: ['spoke-up', 'told-adults'],
        outcomes: [{
          id: 'split',
          weight: 1,
          text: '大人把责任分清楚了。{peer}很久不和你一起走回家。',
          later: '坦白让你干净，也让一段交情裂开。',
          world: {
            addTags: ['told-adults'],
            relations: [
              { id: 'friend', closenessDelta: -2, strainDelta: 2 },
              { id: 'parents', closenessDelta: 1 },
            ],
          },
        }],
      },
      {
        id: 'aside',
        text: '说自己当时不在',
        preview: '你把自己摘出去，谁也不帮。',
        costKind: 'free',
        fragmentTags: ['stayed-quiet', 'stepped-aside'],
        outcomes: [{
          id: 'alone',
          weight: 1,
          text: '没有人再来问你。{peer}自己扛了过去，也没有再找你。',
          later: '你保住了自己，却少了一个可以说闲话的人。',
          world: {
            addTags: ['stepped-aside'],
            relations: [{ id: 'friend', closenessDelta: -1 }],
          },
        }],
      },
    ],
  },
  {
    id: 'trust_ask_help',
    theme: 'trust',
    title: '撑不住的时候',
    text: '一件事把你压到说不出口。{guardian}就在近处，你还没有伸过手。',
    minAge: 17,
    maxAge: 23,
    years: 5,
    sceneKind: 'hearth',
    weight: 5,
    people: [guardian],
    triggerKind: 'era',
    triggerNote: '成年前后的压力自己长了出来。',
    choices: [
      {
        id: 'ask',
        text: '把难处告诉{guardian}',
        preview: '可能得到接住，也可能被看成还没长大。',
        costKind: 'break-habit',
        support: { anyFragmentTags: ['spoke-up'], ifUnsupported: 'cost-break' },
        supportReason: '开口求助并不符合你一直以来的反应，需要 1 人生点。',
        fragmentTags: ['asked-help', 'spoke-up'],
        outcomes: [
          {
            id: 'held',
            weight: 6,
            text: '{guardian}没有笑话你。饭桌上多了一副碗筷的余地，事情缓了一缓。',
            later: '你知道家里至少还能被你麻烦一次。',
            world: {
              addTags: ['asked-help'],
              relations: [{ id: 'parents', closenessDelta: 2 }],
              threads: [{ id: 'family_origin', domain: 'family', intensityDelta: 1 }],
            },
          },
          {
            id: 'judged',
            weight: 4,
            text: '{guardian}帮了你，话却很硬：“以后别把这种事带回家。”',
            later: '求助换来了接住，也换来了新的忌讳。',
            world: {
              addTags: ['asked-help', 'help-costly'],
              relations: [{ id: 'parents', closenessDelta: 1, strainDelta: 2 }],
            },
          },
        ],
      },
      {
        id: 'hold',
        text: '自己先扛着',
        preview: '眼前不必看别人脸色，身体和日子会先被透支。',
        costKind: 'free',
        fragmentTags: ['self-held', 'stayed-quiet'],
        outcomes: [{
          id: 'worn',
          weight: 1,
          text: '你把事情按下去了。夜里睡不稳，白天仍装得像没事。',
          later: '你更习惯一个人撑，也更少让人看见裂口。',
          world: {
            addTags: ['self-held'],
            setFacts: { health: 'warning' },
            marks: [{ id: 'wear', intensityDelta: 1 }],
            relations: [{ id: 'parents', closenessDelta: -1 }],
          },
        }],
      },
      {
        id: 'peer',
        text: '去找{peer}说',
        preview: '同辈也许懂，却未必帮得动。',
        costKind: 'free',
        fragmentTags: ['asked-peer'],
        outcomes: [{
          id: 'shared',
          weight: 1,
          text: '{peer}听完只说“我懂”。你们谁也没有更好的办法，但那晚你没有那么空。',
          later: '你开始把难处往同辈那里放，而不是家里。',
          world: {
            addTags: ['asked-peer'],
            relations: [{
              id: 'friend',
              kind: 'friend',
              label: '同伴',
              closenessDelta: 1,
            }],
          },
        }],
      },
    ],
  },
  {
    id: 'trust_share_blame',
    theme: 'trust',
    title: '一起承担',
    text: '{peer}在事情里犯了错。有人已经在看你：你是把人推开，还是站到同一边。',
    minAge: 24,
    maxAge: 34,
    years: 6,
    sceneKind: 'service',
    weight: 7,
    people: [peer, elder],
    triggerKind: 'chance',
    triggerNote: '成年后的过错不再只是挨骂，它会改写机会。',
    choices: [
      {
        id: 'share',
        text: '承认自己也在场，一起承担',
        preview: '可能失去一次晋升，却把交情坐实。',
        costKind: 'break-habit',
        support: {
          anyFragmentTags: ['covered-friend', 'asked-help'],
          understandingIds: ['truth-costs-protection'],
          ifUnsupported: 'cost-break',
        },
        supportReason: '你曾经因坦白受罚，这次开口共同承担需要 1 人生点。',
        fragmentTags: ['shared-blame', 'spoke-up'],
        outcomes: [{
          id: 'lost-chance',
          weight: 1,
          text: '{elder}把机会给了别人。{peer}却在事后说：“以后有我在。”',
          later: '你少了一级台阶，多了一个靠得住的人。',
          world: {
            addTags: ['shared-blame', 'lost-promotion'],
            setFacts: { occupation: 'employed' },
            relations: [
              { id: 'friend', closenessDelta: 3, strainDelta: -1 },
              { id: 'mentor', closenessDelta: -1 },
            ],
            threads: [{ id: 'career_life', domain: 'career', intensityDelta: -1 }],
          },
        }],
      },
      {
        id: 'distance',
        text: '把责任划清，保护自己',
        preview: '位置还在，{peer}会记住你抽身的那一下。',
        costKind: 'free',
        fragmentTags: ['stepped-aside', 'self-held'],
        outcomes: [{
          id: 'kept-place',
          weight: 1,
          text: '你说清楚了自己的边界。机会还在，走廊里的招呼却少了。',
          later: '你保住了位置，也学会了在关键处把自己摘出去。',
          world: {
            addTags: ['kept-place', 'stepped-aside'],
            relations: [{ id: 'friend', closenessDelta: -2, strainDelta: 2 }],
            threads: [{ id: 'career_life', domain: 'career', intensityDelta: 1 }],
          },
        }],
      },
      {
        id: 'quiet-help',
        text: '当面不认，私下帮{peer}补救',
        preview: '两边都不得罪，两边也都不彻底。',
        costKind: 'free',
        fragmentTags: ['hid-and-safe', 'quiet-help'],
        outcomes: [{
          id: 'half',
          weight: 1,
          text: '公开场合你没有站出来。夜里你帮{peer}把漏洞补上了，谁也没有谢谁。',
          later: '你习惯用私下的好，去抵公开的退缩。',
          world: {
            addTags: ['quiet-help'],
            setFacts: { secret: 'kept' },
            relations: [{ id: 'friend', closenessDelta: 1, strainDelta: 1 }],
          },
        }],
      },
    ],
  },
  {
    id: 'trust_workplace',
    theme: 'trust',
    title: '台上的失误',
    text: '一次公开的错已经发生。{elder}等你解释。你可以认，可以推，也可以把话藏进程序里。',
    minAge: 30,
    maxAge: 42,
    years: 6,
    sceneKind: 'service',
    weight: 5,
    people: [elder, peer],
    triggerKind: 'era',
    triggerNote: '工作把对错放到了台面上。',
    choices: [
      {
        id: 'admit',
        text: '当众承认失误',
        preview: '信用或许还在，眼前的台阶会先抽走。',
        costKind: 'break-habit',
        support: { anyFragmentTags: ['shared-blame', 'spoke-up'], ifUnsupported: 'cost-break' },
        supportReason: '当众承认并不符合你更熟的保护自己的方式，需要 1 人生点。',
        fragmentTags: ['spoke-up', 'workplace-admitted'],
        outcomes: [{
          id: 'respected',
          weight: 1,
          text: '{elder}点了点头，机会却给了更稳的人。有人开始愿意把难事交给你。',
          later: '你以信用换位置，信用比位置活得更久。',
          world: {
            addTags: ['workplace-admitted'],
            relations: [{ id: 'mentor', closenessDelta: 1 }, { id: 'friend', closenessDelta: 1 }],
            threads: [{ id: 'career_life', domain: 'career', intensityDelta: -1 }],
          },
        }],
      },
      {
        id: 'bury',
        text: '把责任写进流程，不点名',
        preview: '事情会过去，谁也不必丢脸。',
        costKind: 'free',
        fragmentTags: ['workplace-hid', 'secret-kept'],
        outcomes: [{
          id: 'smooth',
          weight: 1,
          text: '报告写得很干净。没有人被点名，也没有人真正被接住。',
          later: '你学会让制度替你承担难堪。',
          world: {
            addTags: ['workplace-hid'],
            setFacts: { secret: 'kept' },
            relations: [{ id: 'mentor', closenessDelta: 1 }],
          },
        }],
      },
      {
        id: 'shift',
        text: '把缺口推到别人的环节',
        preview: '你过关，{peer}会背上这笔。',
        costKind: 'free',
        fragmentTags: ['stepped-aside', 'shifted-blame'],
        outcomes: [{
          id: 'clear',
          weight: 1,
          text: '你过了这一关。{peer}看你的眼神从此很浅。',
          later: '位置更稳，能交心的人更少。',
          world: {
            addTags: ['shifted-blame'],
            relations: [{ id: 'friend', closenessDelta: -3, strainDelta: 2 }],
            threads: [{ id: 'career_life', domain: 'career', intensityDelta: 2 }],
          },
        }],
      },
    ],
  },
  {
    id: 'trust_old_secret',
    theme: 'trust',
    title: '还没说出口的事',
    text: '到了可以慢慢说话的年纪。{guardian}或已经不在近处的人，仍被你藏着一件旧事。',
    minAge: 52,
    maxAge: 70,
    years: 6,
    sceneKind: 'dusk',
    weight: 4,
    people: [guardian, peer],
    triggerKind: 'era',
    triggerNote: '晚年把没说完的话又推到嘴边。',
    choices: [
      {
        id: 'tell',
        text: '把旧事说开',
        preview: '关系可能松一口气，也可能掀开旧伤。',
        costKind: 'break-habit',
        support: { anyFragmentTags: ['spoke-up', 'shared-blame'], ifUnsupported: 'cost-break' },
        supportReason: '把藏了很久的话说出来，需要 1 人生点去突破惯常的沉默。',
        fragmentTags: ['secret-shared', 'spoke-up'],
        outcomes: [{
          id: 'opened',
          weight: 1,
          text: '话说完后，屋里静了一会儿。没有人拥抱，也没有人再假装不知道。',
          later: '秘密不再长在你身体里。',
          world: {
            addTags: ['secret-shared'],
            setFacts: { secret: 'shared' },
            relations: [{ id: 'parents', closenessDelta: 1, strainDelta: -1 }, { id: 'friend', closenessDelta: 1 }],
          },
        }],
      },
      {
        id: 'keep',
        text: '继续带到土里',
        preview: '日子平静，那句话会一直占地方。',
        costKind: 'free',
        fragmentTags: ['secret-kept'],
        outcomes: [{
          id: 'buried',
          weight: 1,
          text: '你把茶壶转了一圈，把话又咽回去。有些事就这样成了这一世的形状。',
          later: '你把完整的自己留了一部分不给人看。',
          world: {
            addTags: ['secret-kept'],
            setFacts: { secret: 'kept' },
            relations: [{ id: 'parents', closenessDelta: -1 }],
          },
        }],
      },
      {
        id: 'write',
        text: '写成一封不必寄出的信',
        preview: '你对自己说清楚，却不必强迫谁听。',
        costKind: 'free',
        fragmentTags: ['secret-kept', 'wrote-it'],
        outcomes: [{
          id: 'letter',
          weight: 1,
          text: '信写完就锁进抽屉。你轻松了一些，世界没有因此震动。',
          later: '你允许真相存在，却不要求它被接住。',
          world: {
            addTags: ['wrote-it'],
            relations: [{ id: 'parents', strainDelta: -1 }],
          },
        }],
      },
    ],
  },
  {
    id: 'belong_leave_town',
    theme: 'belonging',
    title: '出镇的机会',
    text: '外面来了一条路。{guardian}没有拦你，也没有送你。你第一次认真想走。',
    minAge: 14,
    maxAge: 19,
    years: 4,
    sceneKind: 'journey',
    weight: 6,
    people: [guardian, peer],
    triggerKind: 'era',
    triggerNote: '年纪把远方推到了可及之处。',
    choices: [
      {
        id: 'go',
        text: '跟着机会离开故乡',
        preview: '世界会变大，家里的灯会先暗一截。',
        costKind: 'free',
        fragmentTags: ['left-home'],
        outcomes: [{
          id: 'departed',
          weight: 1,
          text: '车窗外的田很快看不见了。你把{guardian}的话听成了风。',
          later: '离开成了你人生的底色之一。',
          world: {
            addTags: ['left-home'],
            setFacts: { residence: 'city' },
            relations: [{ id: 'parents', closenessDelta: -2 }, { id: 'friend', closenessDelta: -1 }],
            threads: [{ id: 'open_road', domain: 'travel', label: '远行', intensity: 3 }],
          },
          schedule: [{ templateId: 'belong_chance_return', afterYears: 8, windowYears: 10, note: '故乡会再给你一次回头的缝' }],
        }],
      },
      {
        id: 'stay',
        text: '留下，把根按进土里',
        preview: '{peer}还在，路却会从别人脚底下走过。',
        costKind: 'free',
        fragmentTags: ['stayed-home'],
        outcomes: [{
          id: 'rooted',
          weight: 1,
          text: '你看着那班车走了。镇上的日子照旧，你却知道自己选过一次。',
          later: '留下让你更被需要，也更难再把自己拔起来。',
          world: {
            addTags: ['stayed-home'],
            setFacts: { residence: 'hometown' },
            relations: [{ id: 'parents', closenessDelta: 2 }, { id: 'friend', closenessDelta: 1 }],
            threads: [{ id: 'family_origin', domain: 'family', intensityDelta: 2 }],
          },
        }],
      },
      {
        id: 'delay',
        text: '说再等一年',
        preview: '谁也不伤，机会可能不会再来。',
        costKind: 'free',
        fragmentTags: ['delayed-leave'],
        outcomes: [{
          id: 'waited',
          weight: 1,
          text: '你把行李又放回去。一年很快，路却改了班次。',
          later: '拖延本身也成了一种离开的方式。',
          world: {
            addTags: ['delayed-leave'],
            relations: [{ id: 'parents', strainDelta: 1 }],
            threads: [{ id: 'open_road', domain: 'travel', label: '远行', intensity: 1 }],
          },
        }],
      },
    ],
  },
  {
    id: 'belong_first_distance',
    theme: 'belonging',
    title: '渐渐听不清的乡音',
    text: '无论你人在哪，{guardian}的信都变短了。有些话开始要用力气才问得出口。',
    minAge: 18,
    maxAge: 25,
    years: 5,
    sceneKind: 'hearth',
    weight: 5,
    people: [guardian],
    triggerKind: 'era',
    triggerNote: '时间和距离自己会把人拉远。',
    choices: [
      {
        id: 'write',
        text: '主动把近况写回去',
        preview: '你先伸手，关系会热一点。',
        costKind: 'free',
        fragmentTags: ['reached-home'],
        outcomes: [{
          id: 'warmed',
          weight: 1,
          text: '回信来得慢，却来了。有人在纸上叫你的小名。',
          later: '你证明了疏远不是单行道。',
          world: {
            addTags: ['reached-home'],
            relations: [{ id: 'parents', closenessDelta: 2 }],
          },
        }],
      },
      {
        id: 'let',
        text: '让它自己冷下去',
        preview: '少一些愧疚的时刻，也少一个可回去的位置。',
        costKind: 'free',
        fragmentTags: ['grew-distant'],
        outcomes: [{
          id: 'faded',
          weight: 1,
          text: '节庆的问候停了。你发现自己已经想不起家里灶的位置。',
          later: '疏远一旦被你允许，就会自己走完。',
          world: {
            addTags: ['grew-distant'],
            relations: [{ id: 'parents', closenessDelta: -2 }],
          },
        }],
      },
      {
        id: 'visit',
        text: '专程回去一趟',
        preview: '路费和时间都要付，见面也可能比信更尴尬。',
        costKind: 'pursue-opportunity',
        support: { anyTags: ['left-home', 'stayed-home'], ifUnsupported: 'hide' },
        supportReason: '主动回去一趟是在争取已经松动的联系，需要 2 人生点。',
        fragmentTags: ['visited-home', 'reconnected'],
        outcomes: [
          {
            id: 'ok',
            weight: 6,
            text: '饭桌上的话不多，你把碗洗了。临走时{guardian}把一袋炒货塞进你包里。',
            later: '你把回来变成一件可以再发生的事。',
            world: {
              addTags: ['visited-home', 'reconnected'],
              relations: [{ id: 'parents', closenessDelta: 2, strainDelta: -1 }],
            },
          },
          {
            id: 'awkward',
            weight: 4,
            text: '你回去了，话却对不上。两天像做客，第三天你提前走了。',
            later: '争取过，并不保证还能重新住进去。',
            world: {
              addTags: ['visited-home'],
              relations: [{ id: 'parents', strainDelta: 1 }],
            },
          },
        ],
      },
    ],
  },
  {
    id: 'belong_chance_return',
    theme: 'belonging',
    title: '一封叫你回去的信',
    text: '家里来信，说缺人手，或缺一个能做主的人。{guardian}没有命令你，信却写得很短。',
    minAge: 24,
    maxAge: 34,
    years: 5,
    sceneKind: 'hearth',
    weight: 6,
    people: [guardian, partner],
    triggerKind: 'consequence',
    triggerNote: '故乡在你走后仍会提出要求。',
    choices: [
      {
        id: 'return',
        text: '回去撑一段时间',
        preview: '外面的位置会松，家里的灯会重新亮。',
        costKind: 'free',
        fragmentTags: ['returned-home', 'reconnected'],
        outcomes: [{
          id: 'back',
          weight: 1,
          text: '你把外面的钥匙交给别人。灶重新热了，你的名字又出现在门口。',
          later: '你证明人可以回去，尽管回去也要付出。',
          world: {
            addTags: ['returned-home', 'reconnected'],
            setFacts: { residence: 'returned' },
            relations: [{ id: 'parents', closenessDelta: 3 }, { id: 'partner', closenessDelta: -1, strainDelta: 1 }],
            threads: [{ id: 'open_road', domain: 'travel', intensityDelta: -2 }],
          },
        }],
      },
      {
        id: 'send',
        text: '寄钱回去，人先不回',
        preview: '责任被折成数目，人仍在外面。',
        costKind: 'free',
        fragmentTags: ['sent-money', 'grew-distant'],
        outcomes: [{
          id: 'money',
          weight: 1,
          text: '汇款走了。回信只说“知道了”。你把愧疚折进下个月的数目里。',
          later: '你用钱代替了到场。',
          world: {
            addTags: ['sent-money'],
            relations: [{ id: 'parents', closenessDelta: -1, strainDelta: 1 }],
            marks: [{ id: 'means', intensityDelta: -1 }],
          },
        }],
      },
      {
        id: 'refuse',
        text: '回信说，自己已经走远了',
        preview: '界限清楚，门可能会从此关严。',
        costKind: 'break-habit',
        support: { anyFragmentTags: ['left-home', 'new-roots'], ifUnsupported: 'cost-break' },
        supportReason: '把“不回去”说出口，需要 1 人生点去面对被看成抛弃。',
        fragmentTags: ['refused-return', 'left-home'],
        outcomes: [{
          id: 'cut',
          weight: 1,
          text: '信寄出后很久没有回音。你把自己的生活又按实了一分。',
          later: '拒绝回去让你更自由，也更没有来处可退。',
          world: {
            addTags: ['refused-return'],
            relations: [{ id: 'parents', closenessDelta: -3 }],
            setFacts: { residence: 'city' },
          },
        }],
      },
    ],
  },
  {
    id: 'belong_new_roots',
    theme: 'belonging',
    title: '在别处被叫住',
    text: '有人在这个地方开始叫你的名字，像你也该在这里有一席。{partner}看着你。',
    minAge: 26,
    maxAge: 38,
    years: 5,
    sceneKind: 'hearth',
    weight: 5,
    people: [partner, peer],
    triggerKind: 'chance',
    triggerNote: '新的地方不会自动变成家，除非你答应。',
    choices: [
      {
        id: 'root',
        text: '答应在这里成家或扎根',
        preview: '你会有新的归属，旧的来处会再远一截。',
        costKind: 'free',
        fragmentTags: ['new-roots'],
        outcomes: [{
          id: 'settled',
          weight: 1,
          text: '钥匙多了一把。你开始记得这栋楼哪一级会响。',
          later: '新的家要你按时回去。',
          world: {
            addTags: ['new-roots', 'made-home'],
            setFacts: { partnership: 'home', residence: 'city' },
            relations: [{ id: 'partner', kind: 'partner', label: '伴侣', closeness: 7 }],
            threads: [{ id: 'family_own', domain: 'family', label: '自己的家', intensity: 3 }],
          },
        }],
      },
      {
        id: 'hold',
        text: '亲近，却不把钥匙交出去',
        preview: '自由还在，对方会觉得你总留着后路。',
        costKind: 'free',
        fragmentTags: ['guarded-heart'],
        outcomes: [{
          id: 'guarded',
          weight: 1,
          text: '你把靠近停在合适的距离。夜里这城市仍像暂住。',
          later: '你有伴，却没有完全属于任何一处。',
          world: {
            addTags: ['guarded-heart'],
            setFacts: { partnership: 'guarded' },
            relations: [{ id: 'partner', closenessDelta: 1, strainDelta: 1 }],
          },
        }],
      },
      {
        id: 'leave-again',
        text: '在被留住之前先走',
        preview: '没有人能指责你食言，因为你还没答应。',
        costKind: 'free',
        fragmentTags: ['left-again', 'left-home'],
        outcomes: [{
          id: 'moved',
          weight: 1,
          text: '你把箱子又提起。{partner}没有追到车站。',
          later: '离开比留下更熟练，也更难被谁等。',
          world: {
            addTags: ['left-again'],
            setFacts: { residence: 'traveling', partnership: 'parted' },
            relations: [{ id: 'partner', closenessDelta: -2 }],
            threads: [{ id: 'open_road', domain: 'travel', intensityDelta: 2 }],
          },
        }],
      },
    ],
  },
  {
    id: 'belong_leave_again',
    theme: 'belonging',
    title: '再走一次',
    text: '家里或伴侣已经习惯你在。外面又来了一个更远的位置。',
    minAge: 34,
    maxAge: 48,
    years: 6,
    sceneKind: 'journey',
    weight: 5,
    people: [partner, guardian],
    triggerKind: 'thread-conflict',
    triggerNote: '两条线同时要你：留下的人和远方的事。',
    choices: [
      {
        id: 'go',
        text: '再离开一次',
        preview: '事业或见识会涨，家里会把你看成过客。',
        costKind: 'free',
        fragmentTags: ['left-again', 'left-home'],
        outcomes: [{
          id: 'away',
          weight: 1,
          text: '你把季节分成两地。每次回来，家具都像被人轻轻挪过。',
          later: '远行成了你对家的一种亏欠。',
          world: {
            addTags: ['left-again'],
            setFacts: { residence: 'traveling' },
            relations: [{ id: 'partner', strainDelta: 2, closenessDelta: -1 }, { id: 'parents', closenessDelta: -1 }],
            threads: [{ id: 'open_road', domain: 'travel', intensityDelta: 2 }],
          },
        }],
      },
      {
        id: 'stay',
        text: '把远方让给别人',
        preview: '你在，家就稳；你也会想起那条没走的路。',
        costKind: 'free',
        fragmentTags: ['stayed-for-them'],
        outcomes: [{
          id: 'present',
          weight: 1,
          text: '你把聘书退了。晚饭开始准时。有人在门口不再先问你哪天走。',
          later: '留下让你被需要，也让不甘心悄悄发芽。',
          world: {
            addTags: ['stayed-for-them'],
            relations: [{ id: 'partner', closenessDelta: 2, strainDelta: -1 }],
            threads: [{ id: 'open_road', domain: 'travel', intensityDelta: -2 }],
          },
        }],
      },
      {
        id: 'negotiate',
        text: '谈一个来回的办法',
        preview: '可能两头都顾上，也可能两头都不踏实。',
        costKind: 'pursue-opportunity',
        supportReason: '提出一种新的相处方式，是在主动争取，需要 2 人生点。',
        fragmentTags: ['negotiated-distance'],
        outcomes: [
          {
            id: 'works',
            weight: 5,
            text: '你们把日历摊开，标出回来的日子。开始的几个月居然真的做到了。',
            later: '你证明距离可以被安排，只要双方都还肯等。',
            world: {
              addTags: ['negotiated-distance'],
              setFacts: { residence: 'moving' },
              relations: [{ id: 'partner', strainDelta: 1, closenessDelta: 1 }],
            },
          },
          {
            id: 'frays',
            weight: 5,
            text: '办法写在纸上，执行却在夜里散掉。两头的人都开始不信下一班车。',
            later: '争取过的折中，失败时比干脆离开更磨人。',
            world: {
              addTags: ['negotiated-distance'],
              relations: [{ id: 'partner', strainDelta: 2 }],
            },
          },
        ],
      },
    ],
  },
  {
    id: 'belong_late_letter',
    theme: 'belonging',
    title: '一封迟来的信',
    text: '故人的名字又出现了。也许是{guardian}，也许是很久不联系的{peer}。信很短，像试探。',
    minAge: 55,
    maxAge: 74,
    years: 5,
    sceneKind: 'dusk',
    weight: 4,
    people: [guardian, peer],
    triggerKind: 'era',
    triggerNote: '晚年常把旧地址重新递到手上。',
    choices: [
      {
        id: 'reply',
        text: '回信，并约一次见面',
        preview: '可能重逢，也可能发现彼此已经是别人。',
        costKind: 'pursue-opportunity',
        supportReason: '主动联系故人是在争取已经冷掉的关系，需要 2 人生点。',
        fragmentTags: ['reconnected'],
        outcomes: [
          {
            id: 'met',
            weight: 6,
            text: '你们在旧街口认出了对方。话不多，足够把“还在”两个字说完。',
            later: '重逢没有让时光倒流，却让来处重新有了名字。',
            world: {
              addTags: ['reconnected'],
              relations: [{ id: 'parents', closenessDelta: 2 }, { id: 'friend', closenessDelta: 2 }],
            },
          },
          {
            id: 'missed',
            weight: 4,
            text: '你去了，对方却已经搬走。门上的名字是别人的。',
            later: '争取过，并不总能把人找回来。',
            world: {
              addTags: ['tried-reconnect'],
              relations: [{ id: 'friend', closenessDelta: -1 }],
            },
          },
        ],
      },
      {
        id: 'polite',
        text: '回一句平安，不再往下约',
        preview: '礼貌还在，门也不再打开。',
        costKind: 'free',
        fragmentTags: ['grew-distant'],
        outcomes: [{
          id: 'closed',
          weight: 1,
          text: '你写了“近来安好”。信箱此后很安静。',
          later: '你把故人停在合适的距离。',
          world: {
            addTags: ['kept-distance'],
            relations: [{ id: 'friend', closenessDelta: -1 }],
          },
        }],
      },
      {
        id: 'ignore',
        text: '把信压在箱子底',
        preview: '没有波澜，也没有下文。',
        costKind: 'free',
        fragmentTags: ['grew-distant'],
        outcomes: [{
          id: 'boxed',
          weight: 1,
          text: '纸边慢慢黄了。有些门不是被关上的，是再也没有人去敲。',
          later: '你允许一些来处就此结束。',
          world: {
            addTags: ['boxed-past'],
            relations: [{ id: 'parents', closenessDelta: -1 }, { id: 'friend', closenessDelta: -1 }],
          },
        }],
      },
    ],
  },
  {
    id: 'worth_seek_praise',
    theme: 'worth',
    title: '等一句好',
    text: '{guardian}看过你做的东西，或你考的那一回。你站在旁边，等一句比“还行”更明确的话。',
    minAge: 8,
    maxAge: 12,
    years: 4,
    sceneKind: 'childhood',
    weight: 6,
    people: [guardian],
    triggerKind: 'family',
    triggerNote: '家里怎样给认可，会先于你自己的判断。',
    choices: [
      {
        id: 'ask',
        text: '直接问：我这次做得好吗',
        preview: '你把渴望摊开，答案可能很淡。',
        costKind: 'free',
        fragmentTags: ['sought-praise'],
        outcomes: [{
          id: 'thin',
          weight: 1,
          text: '{guardian}说“别骄傲”。你把那四个字听成了还不够。',
          later: '你开始用别人的口，来确认自己有没有价值。',
          world: {
            addTags: ['sought-praise'],
            relations: [{ id: 'parents', strainDelta: 1 }],
            threads: [{ id: 'learning_mind', domain: 'learning', intensityDelta: 1 }],
          },
        }],
      },
      {
        id: 'show',
        text: '把东西做得更好再送上去',
        preview: '你会更能干，也更难停。',
        costKind: 'free',
        fragmentTags: ['sought-praise', 'over-worked'],
        outcomes: [{
          id: 'more',
          weight: 1,
          text: '第二稿换来了一句“这还差不多”。你决定把第三稿也做出来。',
          later: '被需要开始跟超额完成绑在一起。',
          world: {
            addTags: ['over-worked'],
            marks: [{ id: 'clarity', intensityDelta: 1 }],
            threads: [{ id: 'craft_life', domain: 'craft', label: '手艺', intensity: 2 }],
          },
        }],
      },
      {
        id: 'hide',
        text: '把作品收起来，不再等人看',
        preview: '你保护了自己，也少了一个被看见的机会。',
        costKind: 'free',
        fragmentTags: ['hid-work'],
        outcomes: [{
          id: 'drawer',
          weight: 1,
          text: '抽屉关上了。你对自己说：反正他们也不懂。',
          later: '你把价值藏起来，免得它被说轻。',
          world: {
            addTags: ['hid-work'],
            relations: [{ id: 'parents', closenessDelta: -1 }],
          },
        }],
      },
    ],
  },
  {
    id: 'worth_care_kin',
    theme: 'worth',
    title: '家里缺人手',
    text: '{guardian}病了，或弟弟妹妹需要人看。外面的课和机会还在，家里的灶先响了。',
    minAge: 14,
    maxAge: 21,
    years: 5,
    sceneKind: 'hearth',
    weight: 5,
    people: [guardian],
    triggerKind: 'family',
    triggerNote: '照料的需求来自家庭，不是你的选择先发生。',
    choices: [
      {
        id: 'care',
        text: '把时间留给家里',
        preview: '你会被需要，自己的路会慢下来。',
        costKind: 'free',
        fragmentTags: ['cared-kin', 'over-needed'],
        outcomes: [{
          id: 'needed',
          weight: 1,
          text: '你学会熬药和算账。有人说“幸好有你”，你把这句话当成自己的名字。',
          later: '被需要让你有位置，也让你更难把自己抽走。',
          world: {
            addTags: ['cared-kin', 'over-needed'],
            relations: [{ id: 'parents', closenessDelta: 2 }],
            threads: [{ id: 'family_origin', domain: 'family', intensityDelta: 2 }],
            setFacts: { schooling: 'continued' },
          },
        }],
      },
      {
        id: 'split',
        text: '两边都顾，少睡一点',
        preview: '谁也不落，身体会先提出意见。',
        costKind: 'free',
        fragmentTags: ['over-worked', 'cared-kin'],
        outcomes: [{
          id: 'tired',
          weight: 1,
          text: '你两头都到了，两头都不完整。镜子里的人先老了一点。',
          later: '你用透支换来“谁都没丢下”。',
          world: {
            addTags: ['over-worked'],
            setFacts: { health: 'warning' },
            marks: [{ id: 'wear', intensityDelta: 1 }],
            relations: [{ id: 'parents', closenessDelta: 1, strainDelta: 1 }],
          },
        }],
      },
      {
        id: 'keep-path',
        text: '把属于自己的时间保住',
        preview: '路还在，家里会觉得你冷。',
        costKind: 'break-habit',
        support: { anyFragmentTags: ['hid-work', 'sought-praise'], ifUnsupported: 'cost-break' },
        supportReason: '在被需要的时候把自己的路放在前面，需要 1 人生点去突破“有用才配留下”。',
        fragmentTags: ['kept-boundary'],
        outcomes: [{
          id: 'bound',
          weight: 1,
          text: '你说了自己还要去。门关上时里面有人叹气。你在路上把那口气听成了自己仍在。',
          later: '你第一次把边界说出来，尽管它让人失望。',
          world: {
            addTags: ['kept-boundary'],
            relations: [{ id: 'parents', closenessDelta: -1, strainDelta: 1 }],
            threads: [{ id: 'learning_mind', domain: 'learning', intensityDelta: 1 }],
          },
        }],
      },
    ],
  },
  {
    id: 'worth_craft_or_stable',
    theme: 'worth',
    title: '手艺还是稳妥',
    text: '{elder}看过你的手。一边是能安稳吃饭的位置，一边是你真正想做的东西。',
    minAge: 20,
    maxAge: 29,
    years: 6,
    sceneKind: 'craft',
    weight: 6,
    people: [elder, guardian],
    triggerKind: 'chance',
    triggerNote: '社会把“有用”和“想做”同时摊在桌上。',
    choices: [
      {
        id: 'craft',
        text: '走手艺或创作那条更险的路',
        preview: '你会被自己需要，日子会紧一阵。',
        costKind: 'free',
        fragmentTags: ['craft-chosen'],
        outcomes: [{
          id: 'made',
          weight: 1,
          text: '你把名字写在自己的东西上。有人说不稳，你夜里却睡得着。',
          later: '创作成了你证明自己的方式。',
          world: {
            addTags: ['craft-chosen'],
            setFacts: { occupation: 'craft' },
            marks: [{ id: 'tools', intensity: 2 }, { id: 'want', intensity: 1 }],
            threads: [{ id: 'craft_life', domain: 'craft', label: '手艺', intensity: 4 }],
          },
        }],
      },
      {
        id: 'stable',
        text: '接受那份稳妥的工作',
        preview: '饭碗在，想做的东西会变成业余。',
        costKind: 'free',
        fragmentTags: ['stable-chosen'],
        outcomes: [{
          id: 'job',
          weight: 1,
          text: '工牌冰凉，发薪日很准时。抽屉里那点自己的东西渐渐蒙灰。',
          later: '你被一个位置需要，却开始怀疑那是不是你。',
          world: {
            addTags: ['stable-chosen'],
            setFacts: { occupation: 'employed' },
            marks: [{ id: 'job', intensity: 2 }],
            threads: [{ id: 'career_life', domain: 'career', intensity: 3 }],
          },
        }],
      },
      {
        id: 'both',
        text: '白天稳妥，夜里做自己的',
        preview: '两头都要，睡眠会先不够。',
        costKind: 'free',
        fragmentTags: ['over-worked', 'craft-chosen'],
        outcomes: [{
          id: 'split-life',
          weight: 1,
          text: '你过上了两套日子。有人夸你能干，你自己知道那是在透支。',
          later: '你把价值拆成两班倒。',
          world: {
            addTags: ['over-worked'],
            setFacts: { occupation: 'employed', health: 'warning' },
            marks: [{ id: 'job', intensity: 1 }, { id: 'tools', intensity: 1 }, { id: 'wear', intensityDelta: 1 }],
          },
        }],
      },
    ],
  },
  {
    id: 'worth_cannot_refuse',
    theme: 'worth',
    title: '没法拒绝的请求',
    text: '又有人来找你。这次是{peer}或家里。你若拒绝，会像把他们从你的价值里推开。',
    minAge: 28,
    maxAge: 40,
    years: 5,
    sceneKind: 'hearth',
    weight: 6,
    people: [peer, partner],
    triggerKind: 'thread-conflict',
    triggerNote: '被需要已经积累成习惯，下一次请求会来得更理所当然。',
    choices: [
      {
        id: 'yes',
        text: '再答应一次',
        preview: '你仍被需要，边界会更薄。',
        costKind: 'free',
        fragmentTags: ['over-needed'],
        outcomes: [{
          id: 'used',
          weight: 1,
          text: '你把日历又划掉一块。有人松了口气，你的名字成了可以随时叫的工具。',
          later: '答应让你暂时有用，也让下一次更难说不。',
          world: {
            addTags: ['over-needed'],
            relations: [{ id: 'friend', closenessDelta: 1, strainDelta: 1 }, { id: 'partner', strainDelta: 1 }],
            marks: [{ id: 'wear', intensityDelta: 1 }],
          },
        }],
      },
      {
        id: 'no',
        text: '第一次清楚地说不',
        preview: '你会让人失望，也可能终于能喘气。',
        costKind: 'break-habit',
        support: {
          anyFragmentTags: ['kept-boundary'],
          understandingIds: ['worth-is-being-needed', 'boundaries-are-selfish'],
          ifUnsupported: 'cost-break',
        },
        supportReason: '在习惯被需要之后拒绝，需要 1 人生点去突破“拒绝就是自私”。',
        fragmentTags: ['kept-boundary'],
        outcomes: [{
          id: 'stood',
          weight: 1,
          text: '空气僵了一秒。有人说“你变了”。你第一次觉得那不一定是坏话。',
          later: '边界让一些人离开，也让你开始属于自己。',
          world: {
            addTags: ['kept-boundary'],
            relations: [{ id: 'friend', closenessDelta: -1 }, { id: 'partner', closenessDelta: 1 }],
          },
        }],
      },
      {
        id: 'delay',
        text: '说手头先满着，过阵子再看',
        preview: '冲突被推迟，请求不会消失。',
        costKind: 'free',
        fragmentTags: ['delayed-need'],
        outcomes: [{
          id: 'later',
          weight: 1,
          text: '他们走了。你知道过阵子他们还会来，你也还没有真正的理由。',
          later: '推迟让你两头都不痛快。',
          world: {
            addTags: ['delayed-need'],
            relations: [{ id: 'friend', strainDelta: 1 }],
          },
        }],
      },
    ],
  },
  {
    id: 'worth_recognition_deal',
    theme: 'worth',
    title: '被看见的代价',
    text: '{elder}把你推到能被看见的位置，条件是你把某条边界让出去——时间、署名，或对某人的态度。',
    minAge: 36,
    maxAge: 50,
    years: 6,
    sceneKind: 'service',
    weight: 5,
    people: [elder, partner],
    triggerKind: 'chance',
    triggerNote: '认可很少免费，它会来谈条件。',
    choices: [
      {
        id: 'take',
        text: '接受被看见，把边界让出去',
        preview: '名字会亮，家里或自己会先缺一块。',
        costKind: 'free',
        fragmentTags: ['took-recognition', 'over-needed'],
        outcomes: [{
          id: 'seen',
          weight: 1,
          text: '你上了台。掌声很短，缺席很长。有人开始只叫你的头衔。',
          later: '你被更大的地方需要，也更不像自己。',
          world: {
            addTags: ['took-recognition'],
            relations: [{ id: 'mentor', closenessDelta: 2 }, { id: 'partner', closenessDelta: -2, strainDelta: 2 }],
            threads: [{ id: 'career_life', domain: 'career', intensityDelta: 2 }],
          },
        }],
      },
      {
        id: 'refuse',
        text: '拒绝这份要你变形的认可',
        preview: '你保持完整，机会会去找更听话的人。',
        costKind: 'free',
        fragmentTags: ['kept-boundary', 'refused-stage'],
        outcomes: [{
          id: 'whole',
          weight: 1,
          text: '位置给了别人。你回家吃了一顿热的。名字小一些，人还在。',
          later: '你把完整的自己看得比被需要更重。',
          world: {
            addTags: ['refused-stage', 'kept-boundary'],
            relations: [{ id: 'mentor', closenessDelta: -1 }, { id: 'partner', closenessDelta: 2 }],
          },
        }],
      },
      {
        id: 'bargain',
        text: '把条件往回谈一截',
        preview: '可能谈成，也可能两边都不讨好。',
        costKind: 'pursue-opportunity',
        supportReason: '提出新的合作方式是在主动争取，需要 2 人生点。',
        fragmentTags: ['bargained-worth'],
        outcomes: [
          {
            id: 'ok',
            weight: 5,
            text: '{elder}皱眉，最后仍点了头。你上了台，却把夜里的时间留了下来。',
            later: '你证明认可也可以谈判。',
            world: {
              addTags: ['bargained-worth'],
              relations: [{ id: 'mentor', closenessDelta: 1 }, { id: 'partner', strainDelta: -1 }],
            },
          },
          {
            id: 'no',
            weight: 5,
            text: '对方说没有商量。你既没有位置，也没有把拒绝说得漂亮。',
            later: '争取失败时，人会怀疑自己是不是不该开口。',
            world: {
              addTags: ['bargained-worth'],
              relations: [{ id: 'mentor', closenessDelta: -1 }],
            },
          },
        ],
      },
    ],
  },
  {
    id: 'worth_still_needed',
    theme: 'worth',
    title: '还有谁叫你',
    text: '年纪到了，位置开始往年轻人手里递。有人问你要不要继续被需要，或以别的方式在。',
    minAge: 55,
    maxAge: 74,
    years: 5,
    sceneKind: 'dusk',
    weight: 4,
    people: [elder, partner],
    triggerKind: 'era',
    triggerNote: '晚年把“有用”这个问题又问了一遍。',
    choices: [
      {
        id: 'hold-post',
        text: '尽量留在原来的位置上',
        preview: '你仍被制度需要，也更难把位置交给别人。',
        costKind: 'free',
        fragmentTags: ['over-needed'],
        outcomes: [{
          id: 'stayed',
          weight: 1,
          text: '你又签了一年。会议室的椅子还认识你的背。有人开始在背后看表。',
          later: '你把被需要延长到了它开始发硬的时候。',
          world: {
            addTags: ['held-post'],
            setFacts: { occupation: 'employed' },
            relations: [{ id: 'mentor', strainDelta: 1 }],
          },
        }],
      },
      {
        id: 'teach',
        text: '把本事交给后来的人',
        preview: '你的名字会淡，你做过的事会留下。',
        costKind: 'free',
        fragmentTags: ['passed-on'],
        outcomes: [{
          id: 'handed',
          weight: 1,
          text: '你把抽屉钥匙交出去。有人做得不如你，你忍住了去改。',
          later: '你开始以成全别人的方式存在。',
          world: {
            addTags: ['passed-on'],
            setFacts: { occupation: 'semi_retired' },
            relations: [{ id: 'mentor', closenessDelta: 1 }],
            threads: [{ id: 'career_life', domain: 'career', intensityDelta: -2 }],
          },
        }],
      },
      {
        id: 'own',
        text: '去过一段不再被叫去的日子',
        preview: '清静会来，空虚也可能来。',
        costKind: 'break-habit',
        support: { anyFragmentTags: ['kept-boundary', 'refused-stage'], ifUnsupported: 'cost-break' },
        supportReason: '不再靠被需要来证明自己，需要 1 人生点。',
        fragmentTags: ['kept-boundary', 'chose-quiet'],
        outcomes: [{
          id: 'quiet',
          weight: 1,
          text: '电话少了。你开始把早上的光看成一件事。没有人叫你，你仍在。',
          later: '你把价值从呼召里轻轻拿了出来。',
          world: {
            addTags: ['chose-quiet'],
            setFacts: { occupation: 'retired' },
            relations: [{ id: 'partner', closenessDelta: 1 }],
          },
        }],
      },
    ],
  },
  {
    id: 'cross_go_with_trusted',
    theme: 'trust',
    crossThemes: ['trust', 'belonging'],
    title: '跟我一起走',
    text: '{peer}要离开，并伸手叫你。信任和归属在同一天要你表态。',
    minAge: 18,
    maxAge: 28,
    years: 5,
    sceneKind: 'journey',
    weight: 4,
    people: [peer, guardian],
    triggerKind: 'thread-conflict',
    triggerNote: '被信任的人把远方带到你面前。',
    choices: [
      {
        id: 'go',
        text: '相信{peer}，一起走',
        preview: '交情坐实，故乡会更远。',
        costKind: 'free',
        fragmentTags: ['left-home', 'covered-friend'],
        outcomes: [{
          id: 'together',
          weight: 1,
          text: '你们把行李放在同一侧。路上有人靠得住，家里有人会说你被带走了。',
          later: '你把信任押在同行上。',
          world: {
            addTags: ['left-home', 'went-with-peer'],
            setFacts: { residence: 'traveling' },
            relations: [{ id: 'friend', closenessDelta: 3 }, { id: 'parents', closenessDelta: -2 }],
          },
        }],
      },
      {
        id: 'stay',
        text: '留下，让{peer}自己走',
        preview: '你对家里守信，对同伴食言。',
        costKind: 'free',
        fragmentTags: ['stayed-home', 'stepped-aside'],
        outcomes: [{
          id: 'waved',
          weight: 1,
          text: '你去送行。{peer}笑了一下，没有再回头。',
          later: '你把归属留给原地，把那个人变成故事。',
          world: {
            addTags: ['stayed-home', 'let-peer-go'],
            relations: [{ id: 'friend', closenessDelta: -2 }, { id: 'parents', closenessDelta: 1 }],
          },
        }],
      },
      {
        id: 'later',
        text: '说自己随后就来',
        preview: '两边都听见承诺，随后可能不会发生。',
        costKind: 'free',
        fragmentTags: ['delayed-leave'],
        outcomes: [{
          id: 'promise',
          weight: 1,
          text: '你把“随后”说得很真。季节换了两回，车票还在抽屉里。',
          later: '未兑现的同行成了一件新的心事。',
          world: {
            addTags: ['unkept-follow'],
            setFacts: { promise: 'made' },
            relations: [{ id: 'friend', strainDelta: 2 }],
          },
        }],
      },
    ],
  },
  {
    id: 'cross_hide_to_keep_place',
    theme: 'worth',
    crossThemes: ['trust', 'worth'],
    title: '位置要你瞒',
    text: '你被需要的那个位置，要求你把一件错事或一个人的名字按下去。',
    minAge: 24,
    maxAge: 36,
    years: 5,
    sceneKind: 'service',
    weight: 4,
    people: [elder, peer],
    triggerKind: 'thread-conflict',
    triggerNote: '被需要与坦白在同一件事里打架。',
    choices: [
      {
        id: 'hide',
        text: '按下去，保住位置',
        preview: '你仍有用，真话会变成把柄。',
        costKind: 'free',
        fragmentTags: ['workplace-hid', 'secret-kept', 'over-needed'],
        outcomes: [{
          id: 'kept',
          weight: 1,
          text: '位置还在。你开始对镜子练习若无其事。',
          later: '有用和沉默被焊在一起。',
          world: {
            addTags: ['workplace-hid', 'secret-kept'],
            setFacts: { secret: 'kept' },
            relations: [{ id: 'mentor', closenessDelta: 1 }, { id: 'friend', closenessDelta: -1 }],
          },
        }],
      },
      {
        id: 'tell',
        text: '把该说的说出来',
        preview: '位置可能没了，你不必再演。',
        costKind: 'break-habit',
        support: { anyFragmentTags: ['spoke-up', 'shared-blame'], ifUnsupported: 'cost-break' },
        supportReason: '在被需要的位置上坦白，需要 1 人生点。',
        fragmentTags: ['spoke-up', 'lost-promotion'],
        outcomes: [{
          id: 'out',
          weight: 1,
          text: '你说完就被调走了。有人在背后说不识时务，{peer}却松了口气。',
          later: '你用位置换了一句真话。',
          world: {
            addTags: ['spoke-up', 'lost-promotion'],
            relations: [{ id: 'mentor', closenessDelta: -2 }, { id: 'friend', closenessDelta: 2 }],
            threads: [{ id: 'career_life', domain: 'career', intensityDelta: -1 }],
          },
        }],
      },
      {
        id: 'leak',
        text: '不公开，只让该知道的人知道',
        preview: '你两边都不彻底，风险却还在。',
        costKind: 'free',
        fragmentTags: ['quiet-help', 'secret-kept'],
        outcomes: [{
          id: 'side',
          weight: 1,
          text: '你把真相交给一个更安全的耳朵。事情被按住，也留下了把柄。',
          later: '你用半公开换半安全。',
          world: {
            addTags: ['side-channel'],
            setFacts: { secret: 'kept' },
            relations: [{ id: 'friend', closenessDelta: 1, strainDelta: 1 }],
          },
        }],
      },
    ],
  },
  {
    id: 'cross_leave_or_care',
    theme: 'belonging',
    crossThemes: ['belonging', 'worth'],
    title: '走，还是留下照料',
    text: '远行的窗口和照料的请求叠在同一周。{guardian}需要人，路上也需要你。',
    minAge: 22,
    maxAge: 34,
    years: 5,
    sceneKind: 'hearth',
    weight: 4,
    people: [guardian, elder],
    triggerKind: 'thread-conflict',
    triggerNote: '家庭的需要和远方的需要同时到达。',
    choices: [
      {
        id: 'care',
        text: '留下照料',
        preview: '你被家里需要，路会先关闭。',
        costKind: 'free',
        fragmentTags: ['cared-kin', 'stayed-home'],
        outcomes: [{
          id: 'home',
          weight: 1,
          text: '聘书过期了。药熬好了。有人握着你的手说“你是家里的柱子”。',
          later: '你把价值放进了照料里。',
          world: {
            addTags: ['cared-kin', 'stayed-home'],
            relations: [{ id: 'parents', closenessDelta: 3 }],
            threads: [{ id: 'open_road', domain: 'travel', intensityDelta: -2 }],
          },
        }],
      },
      {
        id: 'go',
        text: '仍然走',
        preview: '你成全自己的路，家里会记下这次缺席。',
        costKind: 'free',
        fragmentTags: ['left-home', 'kept-boundary'],
        outcomes: [{
          id: 'away',
          weight: 1,
          text: '你走的那天没有人送。后来的信很客气，客气得像对客人。',
          later: '你把自己的路放在被需要前面。',
          world: {
            addTags: ['left-home', 'kept-boundary'],
            setFacts: { residence: 'city' },
            relations: [{ id: 'parents', closenessDelta: -2, strainDelta: 2 }],
          },
        }],
      },
      {
        id: 'arrange',
        text: '花钱请人照料，自己仍走',
        preview: '责任被安排，感情未必领情。',
        costKind: 'pursue-opportunity',
        supportReason: '用一种新办法同时回应两条线，需要 2 人生点去争取。',
        fragmentTags: ['arranged-care', 'left-home'],
        outcomes: [
          {
            id: 'ok',
            weight: 5,
            text: '你把人手安顿好再走。{guardian}嘴上不说，药没有断。',
            later: '你证明离开不一定等于丢下。',
            world: {
              addTags: ['arranged-care', 'left-home'],
              setFacts: { residence: 'city' },
              relations: [{ id: 'parents', strainDelta: 1 }],
              marks: [{ id: 'means', intensityDelta: -1 }],
            },
          },
          {
            id: 'resent',
            weight: 5,
            text: '请来的人不合习惯。信里只问你什么时候真正回来。',
            later: '安排过的照料，仍可能被看成逃避。',
            world: {
              addTags: ['arranged-care'],
              relations: [{ id: 'parents', closenessDelta: -1, strainDelta: 2 }],
            },
          },
        ],
      },
    ],
  },
  {
    id: 'cross_truth_costs_home',
    theme: 'trust',
    crossThemes: ['trust', 'belonging'],
    title: '实话可能让你失去这个家',
    text: '{partner}问你一件不能再含糊的事。坦白可能让这段归属裂开。',
    minAge: 30,
    maxAge: 45,
    years: 5,
    sceneKind: 'hearth',
    weight: 4,
    people: [partner],
    triggerKind: 'thread-conflict',
    triggerNote: '亲密关系把真话和去留绑在一起。',
    choices: [
      {
        id: 'truth',
        text: '把话说完',
        preview: '你完整，这段关系可能改写或结束。',
        costKind: 'break-habit',
        support: { anyFragmentTags: ['spoke-up', 'secret-shared'], ifUnsupported: 'cost-break' },
        supportReason: '在可能失去归属时仍说真话，需要 1 人生点。',
        fragmentTags: ['spoke-up', 'secret-shared'],
        outcomes: [{
          id: 'rift',
          weight: 1,
          text: '话说完，家还在，空气却换了。有人开始分床，有人开始重新认识你。',
          later: '你没有用谎言续租这个家。',
          world: {
            addTags: ['told-partner', 'secret-shared'],
            setFacts: { secret: 'shared', partnership: 'independent' },
            relations: [{ id: 'partner', closenessDelta: -1, strainDelta: 2 }],
          },
        }],
      },
      {
        id: 'keep',
        text: '把家保住，把话留下',
        preview: '归属还在，你们中间会多一堵墙。',
        costKind: 'free',
        fragmentTags: ['secret-kept', 'new-roots'],
        outcomes: [{
          id: 'wall',
          weight: 1,
          text: '你选了今晚的平静。墙是软的，以后每次靠近都会碰到它。',
          later: '你用一个秘密续上了这段归属。',
          world: {
            addTags: ['secret-kept'],
            setFacts: { secret: 'kept' },
            relations: [{ id: 'partner', strainDelta: 1 }],
          },
        }],
      },
      {
        id: 'leave',
        text: '在被问倒之前先离开这段关系',
        preview: '没有对质，也没有和解。',
        costKind: 'free',
        fragmentTags: ['left-again', 'parted'],
        outcomes: [{
          id: 'gone',
          weight: 1,
          text: '你把钥匙放下。问题没有答案，因为提问的人已经不在同一间屋里。',
          later: '离开让你不必坦白，也让你无处可归。',
          world: {
            addTags: ['parted', 'left-again'],
            setFacts: { partnership: 'parted' },
            relations: [{ id: 'partner', closenessDelta: -3 }],
          },
        }],
      },
    ],
  },
  {
    id: 'cross_art_vs_home',
    theme: 'worth',
    crossThemes: ['belonging', 'worth'],
    title: '作品和家',
    text: '一次真正的创作或手艺机会来了，它要你离开现在的家一段时间。{partner}等你决定。',
    minAge: 28,
    maxAge: 42,
    years: 5,
    sceneKind: 'craft',
    weight: 4,
    people: [partner, elder],
    triggerKind: 'thread-conflict',
    triggerNote: '被看见的机会和被需要的家叠在一起。',
    choices: [
      {
        id: 'art',
        text: '去把那件作品做完',
        preview: '你成全自己的名字，家里会缺席。',
        costKind: 'free',
        fragmentTags: ['craft-chosen', 'left-again'],
        outcomes: [{
          id: 'made',
          weight: 1,
          text: '作品立住了。回家时晚饭已经冷了，有人问你还想不想回来。',
          later: '你用缺席换来了一次被看见。',
          world: {
            addTags: ['craft-chosen', 'left-again'],
            setFacts: { occupation: 'craft' },
            relations: [{ id: 'partner', closenessDelta: -2, strainDelta: 2 }],
            threads: [{ id: 'craft_life', domain: 'craft', intensityDelta: 2 }],
          },
        }],
      },
      {
        id: 'home',
        text: '把这次机会让掉',
        preview: '家还在，你可能反复想起那件没做的东西。',
        costKind: 'free',
        fragmentTags: ['stayed-for-them', 'stable-chosen'],
        outcomes: [{
          id: 'let',
          weight: 1,
          text: '你看着别人把那件作品做完。家里的灯对你很亮，你自己的眼睛有时会暗。',
          later: '你把被需要放在被看见前面。',
          world: {
            addTags: ['stayed-for-them'],
            relations: [{ id: 'partner', closenessDelta: 2 }],
            threads: [{ id: 'craft_life', domain: 'craft', intensityDelta: -1 }],
          },
        }],
      },
      {
        id: 'bring',
        text: '试着把家一起带走，或把作品带回家做',
        preview: '新办法可能两全，也可能两头不到。',
        costKind: 'pursue-opportunity',
        supportReason: '提出一种新的安排是在主动争取，需要 2 人生点。',
        fragmentTags: ['negotiated-distance', 'craft-chosen'],
        outcomes: [
          {
            id: 'ok',
            weight: 5,
            text: '你们把桌子拼到一起。孩子或伴侣在旁边，你仍把东西做完了。',
            later: '你证明创作不必以离开家为代价。',
            world: {
              addTags: ['brought-work-home'],
              relations: [{ id: 'partner', closenessDelta: 1, strainDelta: 1 }],
              threads: [{ id: 'craft_life', domain: 'craft', intensityDelta: 1 }],
            },
          },
          {
            id: 'clash',
            weight: 5,
            text: '家里不是工坊。东西没做成，脾气先做成了。',
            later: '两全的办法有时会把两头都弄皱。',
            world: {
              addTags: ['work-home-clash'],
              relations: [{ id: 'partner', strainDelta: 2 }],
            },
          },
        ],
      },
    ],
  },
  {
    id: 'cross_three_late',
    theme: 'trust',
    crossThemes: ['trust', 'belonging', 'worth'],
    title: '三件事一起来',
    text: '故人要一个说法，家里要你在，还有人问你还要不要被需要。你没有三份自己。',
    minAge: 58,
    maxAge: 78,
    years: 4,
    sceneKind: 'dusk',
    weight: 3,
    people: [peer, partner, guardian],
    triggerKind: 'thread-conflict',
    triggerNote: '收束时，没处理完的线会一起来要你。',
    choices: [
      {
        id: 'people',
        text: '先把人和话说完',
        preview: '位置可以放下，关系会被你放到前面。',
        costKind: 'free',
        fragmentTags: ['reconnected', 'spoke-up'],
        outcomes: [{
          id: 'said',
          weight: 1,
          text: '你把该见的人见了，该说的话说了。有的解开了，有的只是终于被听见。',
          later: '你把收束给了关系，而不是名声。',
          world: {
            addTags: ['late-people-first'],
            relations: [
              { id: 'friend', closenessDelta: 2 },
              { id: 'partner', closenessDelta: 1 },
              { id: 'parents', closenessDelta: 1 },
            ],
            setFacts: { occupation: 'semi_retired' },
          },
        }],
      },
      {
        id: 'post',
        text: '先把还在的职责做完',
        preview: '你仍有用，有些人会等不到你。',
        costKind: 'free',
        fragmentTags: ['over-needed', 'held-post'],
        outcomes: [{
          id: 'duty',
          weight: 1,
          text: '你把最后一份职责做完。电话回得晚了。有的人已经不需要你的解释。',
          later: '你把有用做到了最后，也把一些话留在了没说的地方。',
          world: {
            addTags: ['late-duty-first'],
            relations: [{ id: 'friend', closenessDelta: -1 }, { id: 'partner', strainDelta: 1 }],
          },
        }],
      },
      {
        id: 'choose-one',
        text: '只选一件真正放不下的，其余放下',
        preview: '你会留下缺口，却把真正放不下的那一件收好。',
        costKind: 'break-habit',
        support: { anyFragmentTags: ['kept-boundary'], ifUnsupported: 'cost-break' },
        supportReason: '在还能被三方需要时只选一件，需要 1 人生点。',
        fragmentTags: ['kept-boundary', 'chose-quiet'],
        outcomes: [{
          id: 'one',
          weight: 1,
          text: '你把另外两件事回成“我做不到了”。有人失望。你把自己的最后一段日子拿了回来。',
          later: '你承认人不能把所有线都收到完美的结。',
          world: {
            addTags: ['late-chose-one', 'kept-boundary'],
            setFacts: { occupation: 'retired' },
            relations: [{ id: 'partner', closenessDelta: 1 }],
          },
        }],
      },
    ],
  },
];
