import { GameContent } from '../core/model';
import { HISTORY_FIGURES, HISTORY_REGIONS } from './historyContent';
import { LEGACIES } from './legacyContent';
import { LIFE_STAGES } from './lifeStages';
import { MARKS } from './markContent';
import { SCENARIOS } from './scenarioContent';

export const GAME_CONTENT: GameContent = {
  stages: LIFE_STAGES,
  legacies: LEGACIES,
  marks: MARKS,
  scenarios: SCENARIOS,
  regions: HISTORY_REGIONS,
  figures: HISTORY_FIGURES,
  levels: [
    {
      level: 1,
      requiredExp: 0,
      rewardText: '轮回启程',
    },
    {
      level: 2,
      requiredExp: 50,
      rewardText: '开局多一份余裕，并解锁预见类传承',
      benefits: { attributePointBonus: 1 },
    },
    {
      level: 3,
      requiredExp: 130,
      rewardText: '解锁路线传承与下世顺风',
    },
    {
      level: 4,
      requiredExp: 250,
      rewardText: '天赋候选 +1，解锁稀有天赋、家庭与故事传承',
      benefits: { talentCandidateBonus: 1 },
    },
    {
      level: 5,
      requiredExp: 420,
      rewardText: '永久传承装备槽位 +1',
      benefits: { legacySlotBonus: 1 },
    },
    {
      level: 6,
      requiredExp: 650,
      rewardText: '解锁晚成者天赋、事件与高阶传承',
    },
  ],

  talents: [
    {
      id: 'strong_bones',
      name: '筋骨结实',
      description: '小时候很少生病，恢复也比别人快。',
      unlockLevel: 1,
      effects: { health: 3 },
      tags: ['strong_body'],
      grantMarks: [{ id: 'sturdy', intensity: 2 }],
      world: {
        threads: [{ id: 'body_resilience', domain: 'health', label: '身子骨', intensity: 2 }],
      },
    },
    {
      id: 'quick_learner',
      name: '一点就通',
      description: '面对新知识时，总能更快找到门路。',
      unlockLevel: 1,
      effects: { intellect: 3 },
      tags: ['quick_learner'],
      grantMarks: [{ id: 'clarity', intensity: 2 }],
      world: {
        threads: [{ id: 'learning_mind', domain: 'learning', label: '好学', intensity: 2 }],
      },
    },
    {
      id: 'friendly_face',
      name: '面善',
      description: '陌生人通常愿意先相信你一次。',
      unlockLevel: 1,
      effects: { charm: 3 },
      tags: ['friendly'],
      grantMarks: [{ id: 'presence', intensity: 2 }],
      world: {
        threads: [{ id: 'social_ease', domain: 'relationship', label: '人缘', intensity: 2 }],
      },
    },
    {
      id: 'careful_saver',
      name: '会过日子',
      description: '你很早就明白钱应该花在什么地方。',
      unlockLevel: 1,
      effects: { wealth: 3 },
      tags: ['saver'],
      grantMarks: [{ id: 'savings', intensity: 2 }],
    },
    {
      id: 'steady_heart',
      name: '心性沉稳',
      description: '不急着争一时输赢，反而走得更稳。',
      unlockLevel: 1,
      effects: { health: 1, intellect: 1 },
      tags: ['steady'],
      grantMarks: [{ id: 'vitality', intensity: 1 }, { id: 'clarity', intensity: 1 }],
    },
    {
      id: 'good_listener',
      name: '善于倾听',
      description: '你常能听出别人没有说出口的话。',
      unlockLevel: 1,
      effects: { charm: 2, intellect: 1 },
      tags: ['listener'],
      grantMarks: [{ id: 'presence', intensity: 1 }, { id: 'clarity', intensity: 1 }],
      world: {
        threads: [{ id: 'social_ease', domain: 'relationship', label: '人缘', intensity: 2 }],
      },
    },
    {
      id: 'lucky_pocket',
      name: '偶有横财',
      description: '小概率的好运，总愿意在钱袋旁停一会儿。',
      unlockLevel: 1,
      effects: { wealth: 2, charm: 1 },
      tags: ['lucky'],
      grantMarks: [{ id: 'lucky', intensity: 2 }],
    },
    {
      id: 'outdoor_child',
      name: '野地长大',
      description: '泥土、树枝和远路塑造了你的童年。',
      unlockLevel: 1,
      effects: { health: 2, charm: 1 },
      tags: ['outdoors'],
      grantMarks: [{ id: 'sturdy', intensity: 1 }, { id: 'vitality', intensity: 1 }],
      world: {
        threads: [
          { id: 'body_resilience', domain: 'health', label: '身子骨', intensity: 2 },
          { id: 'open_road', domain: 'travel', label: '野外', intensity: 1 },
        ],
      },
    },
    {
      id: 'second_chance',
      name: '逢险有转机',
      description: '事情最坏的时候，你更容易发现另一条路。',
      unlockLevel: 4,
      effects: { health: 2, wealth: 1 },
      tags: ['second_chance'],
      grantMarks: [{ id: 'lucky', intensity: 1 }, { id: 'vitality', intensity: 1 }],
    },
    {
      id: 'late_bloomer',
      name: '大器晚成',
      description: '年轻时并不起眼，岁月却一直站在你这边。',
      unlockLevel: 6,
      effects: { health: 1, intellect: 1, charm: 1 },
      tags: ['late_bloomer'],
      grantMarks: [{ id: 'clarity', intensity: 1 }],
      world: {
        threads: [{ id: 'learning_mind', domain: 'learning', label: '慢慢长成', intensity: 1 }],
      },
    },
  ],

  families: [
    {
      id: 'working_home',
      name: '安稳的工薪家庭',
      description: '日子不宽裕，但每个月都有确定的盼头。',
      unlockLevel: 1,
      weight: 4,
      effects: { health: 1, wealth: 1 },
      tags: ['stable_home'],
      grantMarks: [{ id: 'means', intensity: 1 }, { id: 'vitality', intensity: 1 }],
      world: {
        setFacts: { household: 'stable' },
        relations: [{ id: 'parents', kind: 'family', label: '家人', closeness: 6 }],
        threads: [{ id: 'family_origin', domain: 'family', label: '原生家庭', intensity: 2 }],
      },
    },
    {
      id: 'bookish_home',
      name: '堆满旧书的家庭',
      description: '家具并不新，书架却总有下一层。',
      unlockLevel: 1,
      weight: 3,
      effects: { intellect: 2, wealth: -1 },
      tags: ['bookish_home'],
      grantMarks: [{ id: 'clarity', intensity: 2 }, { id: 'want', intensity: 1 }],
      world: {
        setFacts: { household: 'books' },
        threads: [
          { id: 'family_origin', domain: 'family', label: '原生家庭', intensity: 1 },
          { id: 'learning_mind', domain: 'learning', label: '家里的书', intensity: 2 },
        ],
      },
    },
    {
      id: 'market_home',
      name: '街角小店之家',
      description: '你从找零和招呼客人中认识了世界。',
      unlockLevel: 1,
      weight: 3,
      effects: { wealth: 2, charm: 1 },
      tags: ['market_home'],
      grantMarks: [{ id: 'means', intensity: 2 }, { id: 'presence', intensity: 1 }],
      world: {
        setFacts: { household: 'shop' },
        threads: [
          { id: 'family_origin', domain: 'family', label: '原生家庭', intensity: 1 },
          { id: 'career_life', domain: 'career', label: '家里的生意', intensity: 2 },
        ],
      },
    },
    {
      id: 'big_family',
      name: '四代同堂之家',
      description: '饭桌总是很挤，也从来不缺说话的人。',
      unlockLevel: 1,
      weight: 3,
      effects: { charm: 2, health: 1 },
      tags: ['big_family'],
      grantMarks: [{ id: 'presence', intensity: 2 }, { id: 'vitality', intensity: 1 }],
      world: {
        setFacts: { household: 'crowded' },
        relations: [
          { id: 'parents', kind: 'family', label: '家人', closeness: 7 },
          { id: 'kin', kind: 'family', label: '亲戚', closeness: 5 },
        ],
        threads: [{ id: 'family_origin', domain: 'family', label: '原生家庭', intensity: 3 }],
      },
    },
    {
      id: 'traveling_home',
      name: '四处迁居之家',
      description: '每隔几年，你就要重新认识一条街道。',
      unlockLevel: 4,
      weight: 2,
      effects: { intellect: 1, charm: 2 },
      tags: ['many_hometowns'],
      grantMarks: [{ id: 'presence', intensity: 1 }, { id: 'clarity', intensity: 1 }],
      world: {
        setFacts: { residence: 'moving', household: 'moving' },
        relations: [{ id: 'parents', kind: 'family', label: '家人', closeness: 4 }],
        threads: [
          { id: 'family_origin', domain: 'family', label: '原生家庭', intensity: 1 },
          { id: 'open_road', domain: 'travel', label: '迁居', intensity: 2 },
        ],
      },
    },
  ],

  events: [
    {
      id: 'toddler_sun',
      minAge: 1,
      maxAge: 5,
      text: '你追着窗边的光斑爬了很久，终于学会稳稳站住。',
      weight: 1,
      effects: { health: 1 },
    },
    {
      id: 'bedtime_story',
      minAge: 1,
      maxAge: 5,
      text: '睡前故事讲了一遍又一遍，你开始替故事编新的结尾。',
      weight: 2,
      once: true,
      effects: { intellect: 1 },
      addTags: ['loves_stories'],
    },
    {
      id: 'childhood_fever',
      minAge: 2,
      maxAge: 8,
      text: '一场高烧让全家守了你一夜。天亮时，你终于退烧了。',
      weight: 1,
      once: true,
      effects: { health: -2 },
    },
    {
      id: 'muddy_knees',
      minAge: 3,
      maxAge: 8,
      text: '你在雨后的空地摔得满腿是泥，却笑着又跑了一圈。',
      weight: 2,
      once: true,
      effects: { health: 1, charm: 1 },
      condition: { requiredTalentIds: ['outdoor_child'] },
    },
    {
      id: 'first_school_day',
      minAge: 6,
      maxAge: 9,
      text: '第一次走进教室，你记住了同桌的名字，也记住了回家的路。',
      weight: 4,
      once: true,
      effects: { intellect: 1, charm: 1 },
      addTags: ['started_school'],
      domains: ['learning', 'relationship'],
      world: {
        setFacts: { schooling: 'started' },
        threads: [{ id: 'school_life', domain: 'learning', label: '上学', intensity: 2 }],
      },
    },
    {
      id: 'library_corner',
      minAge: 7,
      maxAge: 13,
      text: '你发现图书角有一本从没人借过的书，并把它读到了最后。',
      weight: 2,
      once: true,
      effects: { intellect: 2 },
      addTags: ['library_regular'],
    },
    {
      id: 'broken_window',
      minAge: 8,
      maxAge: 14,
      text: '球打碎了邻居的窗，屋里的人很快走到门口。',
      weight: 2,
      once: true,
      themes: ['relationship', 'family'],
      choices: [
        {
          id: 'confess',
          text: '主动承认并慢慢赔偿',
          preview: '损失家底，但会留下可靠的印象',
          outcomes: [{
            id: 'earned_trust',
            weight: 1,
            text: '你攒了很久零花钱才赔清，对方从此记住了你的担当。',
            effects: { charm: 2, wealth: -1 },
            addTags: ['takes_responsibility'],
            world: {
              relations: [{ id: 'neighbor', kind: 'community', label: '邻居', closeness: 4 }],
              threads: [{ id: 'responsibility', domain: 'relationship', label: '被人记得的担当', intensity: 2 }],
            },
            schedule: [{ eventId: 'neighbor_trust', afterYears: 5, windowYears: 3 }],
          }],
        },
        {
          id: 'hide',
          text: '装作什么也不知道',
          preview: '暂时没有损失，但可能失去信任',
          outcomes: [{
            id: 'secret_kept',
            weight: 1,
            text: '事情没有查到你头上，可每次路过那扇窗，你都会加快脚步。',
            effects: { intellect: 1, charm: -1 },
            addTags: ['hid_mistake'],
            world: {
              relations: [{ id: 'neighbor', kind: 'community', label: '邻居', closeness: 1, strainDelta: 2 }],
            },
          }],
        },
      ],
    },
    {
      id: 'neighbor_trust',
      minAge: 13,
      maxAge: 20,
      text: '当年的邻居记得你的担当，把一份可靠的假期工作介绍给了你。',
      weight: 5,
      once: true,
      themes: ['career', 'relationship'],
      effects: { wealth: 2, charm: 1 },
      condition: { requiredTags: ['takes_responsibility'] },
      addTags: ['trusted_young'],
      world: {
        relations: [{ id: 'neighbor', closenessDelta: 2 }],
        threads: [{ id: 'career_life', domain: 'career', label: '谋生', intensity: 2 }],
      },
    },
    {
      id: 'school_sports',
      minAge: 9,
      maxAge: 15,
      text: '你参加了校运会。名次普通，但坚持跑到了终点。',
      weight: 2,
      once: true,
      effects: { health: 2 },
    },
    {
      id: 'childhood_allowance',
      minAge: 7,
      maxAge: 15,
      text: '你把零花钱分成几只纸袋，第一次为未来留下了一点余额。',
      weight: 2,
      once: true,
      effects: { wealth: 2 },
      condition: { requiredTalentIds: ['careful_saver'] },
    },
    {
      id: 'ordinary_school_year',
      minAge: 6,
      maxAge: 17,
      text: '这一年在作业、铃声和逐渐熟悉的同学中平稳过去。',
      weight: 1,
      effects: { intellect: 1 },
    },
    {
      id: 'teen_friend',
      minAge: 13,
      maxAge: 19,
      text: '你遇见一个能谈到深夜的朋友，许多心事第一次有了去处。',
      weight: 3,
      once: true,
      effects: { charm: 2 },
      addTags: ['lifelong_friend'],
      domains: ['relationship'],
      world: {
        relations: [{ id: 'friend', kind: 'friend', label: '故人', closeness: 6 }],
        threads: [{ id: 'friendship', domain: 'relationship', label: '友情', intensity: 3 }],
      },
    },
    {
      id: 'exam_season',
      minAge: 15,
      maxAge: 19,
      text: '漫长的备考季压在眼前，你必须决定怎样分配最后几个月。',
      weight: 3,
      once: true,
      themes: ['learning', 'health'],
      choices: [
        {
          id: 'study_hard',
          text: '把时间都押在书桌上',
          preview: '心智明显增加，体魄受损',
          outcomes: [{
            id: 'hard_work_paid',
            weight: 1,
            text: '疲惫没有白费，你第一次看见专注积累出的距离。',
            effects: { intellect: 3, health: -1 },
            addTags: ['finished_exam', 'exam_focus'],
            world: {
              setFacts: { schooling: 'exam' },
              threads: [{ id: 'school_life', domain: 'learning', label: '备考', intensity: 4 }],
            },
          }],
        },
        {
          id: 'keep_balance',
          text: '维持学习与生活的平衡',
          preview: '心智和人缘小幅增加',
          outcomes: [{
            id: 'balanced_season',
            weight: 1,
            text: '结果不算耀眼，但你没有在抵达之前耗尽自己。',
            effects: { intellect: 1, charm: 1 },
            addTags: ['finished_exam', 'kept_balance'],
            world: {
              setFacts: { schooling: 'exam' },
              threads: [{ id: 'school_life', domain: 'learning', label: '备考', intensity: 2 }],
            },
          }],
        },
        {
          id: 'learn_practical_skill',
          text: '把一部分时间用于实用技能',
          preview: '偏向手艺和早期工作路线',
          condition: { requiredCapabilityTags: ['practical_path'] },
          outcomes: [{
            id: 'practical_foundation',
            weight: 1,
            text: '你没有只盯着分数，还提前摸到了一门可以安身的本事。',
            effects: { intellect: 1, wealth: 1 },
            addTags: ['finished_exam', 'practical_foundation'],
          }],
        },
        {
          id: 'ask_deeper_questions',
          text: '追问课本之外的问题',
          preview: '开启更深的求学路线',
          condition: { requiredCapabilityTags: ['learning_legacy'] },
          outcomes: [{
            id: 'questions_opened',
            weight: 1,
            text: '答案没有变简单，但你学会了提出更好的问题。',
            effects: { intellect: 3, charm: 1 },
            addTags: ['finished_exam', 'deep_questions'],
          }],
        },
      ],
    },
    {
      id: 'weekend_job',
      minAge: 15,
      maxAge: 21,
      text: '你做了一份周末兼职，工资不多，却第一次由自己决定怎么花。',
      weight: 2,
      once: true,
      effects: { wealth: 2, health: -1 },
      addTags: ['worked_early'],
      domains: ['career'],
      world: {
        threads: [{ id: 'career_life', domain: 'career', label: '谋生', intensity: 2 }],
      },
    },
    {
      id: 'small_stage',
      minAge: 14,
      maxAge: 20,
      text: '你硬着头皮站上小礼堂的舞台，掌声比想象中更温暖。',
      weight: 2,
      once: true,
      effects: { charm: 2 },
    },
    {
      id: 'youthful_year',
      minAge: 13,
      maxAge: 20,
      text: '你开始拥有自己的秘密，也第一次认真想象未来。',
      weight: 1,
      effects: { intellect: 1 },
    },
    {
      id: 'leave_hometown',
      minAge: 18,
      maxAge: 25,
      text: '熟悉的街道已经容不下所有设想，你站在留下与远行之间。',
      weight: 3,
      once: true,
      themes: ['travel', 'career', 'family'],
      choices: [
        {
          id: 'stay_near_home',
          text: '留在熟悉的人身边',
          preview: '生活更稳定，未来偏向本地关系',
          outcomes: [{
            id: 'local_roots',
            weight: 1,
            text: '你很快站稳脚跟，也开始成为别人需要时能找到的人。',
            effects: { wealth: 1, charm: 1 },
            addTags: ['stayed_hometown'],
            world: {
              setFacts: { residence: 'hometown' },
              relations: [{ id: 'parents', closenessDelta: 1 }],
              threads: [{ id: 'family_origin', domain: 'family', label: '原生家庭', intensityDelta: 1 }],
            },
            schedule: [{ eventId: 'local_roots_echo', afterYears: 5, windowYears: 4 }],
          }],
        },
        {
          id: 'go_to_city',
          text: '拖着行李去陌生城市',
          preview: '付出家底，换取见识与城市机会',
          outcomes: [{
            id: 'city_beginning',
            weight: 1,
            text: '最初的日子并不容易，但你学会了独自处理生活。',
            effects: { intellect: 2, wealth: -2 },
            addTags: ['left_hometown'],
            world: {
              setFacts: { residence: 'city' },
              threads: [{ id: 'city_life', domain: 'travel', label: '城市生活', intensity: 3 }],
            },
            schedule: [{ eventId: 'city_crossroads', afterYears: 4, windowYears: 4 }],
          }],
        },
        {
          id: 'wander_first',
          text: '先去远方走一圈再决定',
          preview: '偏向远行与开放路线',
          condition: { requiredCapabilityTags: ['travel_path'] },
          outcomes: [{
            id: 'wide_horizon',
            weight: 1,
            text: '你没有立刻找到归处，却发现世界远比地图上的名字具体。',
            effects: { intellect: 1, charm: 2, wealth: -1 },
            addTags: ['left_hometown', 'young_traveler'],
            world: {
              setFacts: { residence: 'traveling' },
              threads: [{ id: 'open_road', domain: 'travel', label: '远行', intensity: 3 }],
            },
          }],
        },
      ],
    },
    {
      id: 'local_roots_echo',
      minAge: 23,
      maxAge: 34,
      text: '多年前选择留下，使你成了这条街上消息最灵通也最可靠的人。',
      weight: 5,
      once: true,
      themes: ['family', 'relationship', 'career'],
      effects: { charm: 2, wealth: 1 },
      condition: { requiredTags: ['stayed_hometown'] },
      addTags: ['local_anchor'],
    },
    {
      id: 'city_crossroads',
      minAge: 22,
      maxAge: 34,
      text: '当年远行认识的人递来一个新机会，你终于不再只是城市里的陌生名字。',
      weight: 5,
      once: true,
      themes: ['career', 'relationship'],
      effects: { wealth: 2, charm: 1 },
      condition: { requiredTags: ['left_hometown'] },
      addTags: ['city_foothold'],
    },
    {
      id: 'first_job',
      minAge: 19,
      maxAge: 28,
      text: '几条不同的工作道路同时出现，你知道第一步会留下很久的痕迹。',
      weight: 4,
      once: true,
      themes: ['career', 'craft'],
      choices: [
        {
          id: 'stable_job',
          text: '接受稳定但普通的职位',
          preview: '稳定增加家底，稍微消耗体魄',
          outcomes: [{
            id: 'name_on_badge',
            weight: 1,
            text: '工作不算体面，但你的名字第一次印在了工牌上。',
            effects: { wealth: 2, health: -1 },
            addTags: ['has_career'],
            world: {
              setFacts: { occupation: 'employed' },
              marks: [{ id: 'job', intensity: 2 }],
              threads: [{ id: 'career_life', domain: 'career', label: '谋生', intensity: 4 }],
            },
          }],
        },
        {
          id: 'learn_a_craft',
          text: '跟着师傅从基本功学起',
          preview: '获得手艺与长期学习路线',
          outcomes: [{
            id: 'craft_apprentice',
            weight: 1,
            text: '重复的练习很慢，却让你拥有了一件不会轻易失去的东西。',
            effects: { intellect: 2, wealth: 1 },
            addTags: ['has_craft'],
            world: {
              setFacts: { occupation: 'craft' },
              marks: [{ id: 'tools', intensity: 2 }],
              threads: [
                { id: 'craft_life', domain: 'craft', label: '手艺', intensity: 4 },
                { id: 'career_life', domain: 'career', label: '谋生', intensity: 2 },
              ],
            },
          }],
        },
        {
          id: 'build_own_thing',
          text: '把时间押在自己的小计划上',
          preview: '风险较高，成功时打开创造路线',
          condition: { requiredMarks: { clarity: 2 }, requiredCapabilityTags: ['bold_path'] },
          outcomes: [
            {
              id: 'early_prototype',
              weight: 2,
              text: '成果还粗糙，却已经有人愿意认真听你介绍。',
              effects: { intellect: 2, wealth: -1 },
              addTags: ['built_something'],
              world: {
                setFacts: { occupation: 'venture' },
                threads: [{ id: 'career_life', domain: 'career', label: '自己的事', intensity: 4 }],
              },
              schedule: [{ eventId: 'side_project', afterYears: 2, windowYears: 5 }],
            },
            {
              id: 'costly_lesson',
              weight: 1,
              text: '计划没有走远，但失败把真实的门槛一一指给了你。',
              effects: { intellect: 2, wealth: -2 },
              addTags: ['early_failure'],
            },
          ],
        },
        {
          id: 'inherit_craft_memory',
          text: '循着前世手上的记忆选择手艺',
          preview: '以更低代价进入手艺路线',
          condition: { requiredCapabilityTags: ['craft_legacy'] },
          outcomes: [{
            id: 'remembered_craft',
            weight: 1,
            text: '陌生的工具落在手里，却像已经练习过许多年。',
            effects: { intellect: 2, wealth: 2 },
            addTags: ['has_craft', 'remembered_craft'],
            world: {
              setFacts: { occupation: 'craft' },
              threads: [{ id: 'craft_life', domain: 'craft', label: '手艺', intensity: 4 }],
            },
          }],
        },
      ],
    },
    {
      id: 'apprentice_years',
      minAge: 18,
      maxAge: 28,
      text: '你跟着一位老师傅学手艺，重复的练习慢慢变成了本事。',
      weight: 2,
      once: true,
      effects: { intellect: 2, wealth: 1 },
      addTags: ['has_craft'],
      domains: ['craft', 'career'],
      world: {
        setFacts: { occupation: 'craft' },
        threads: [{ id: 'craft_life', domain: 'craft', label: '手艺', intensity: 3 }],
      },
    },
    {
      id: 'first_love',
      minAge: 18,
      maxAge: 30,
      text: '你认真喜欢上一个人，也第一次需要决定怎样面对亲密。',
      weight: 3,
      once: true,
      themes: ['relationship', 'family'],
      choices: [
        {
          id: 'open_heart',
          text: '坦率地走近对方',
          preview: '增加人缘，并可能走向共同生活',
          outcomes: [{
            id: 'love_shared',
            weight: 1,
            text: '不论以后是否同行，这份坦率都改变了你理解亲密的方式。',
            effects: { charm: 2 },
            addTags: ['has_loved'],
            world: {
              setFacts: { partnership: 'loved' },
              relations: [{ id: 'partner', kind: 'partner', label: '恋人', closeness: 6 }],
              threads: [{ id: 'partnership', domain: 'relationship', label: '亲密', intensity: 3 }],
            },
            schedule: [{ eventId: 'make_a_home', afterYears: 5, windowYears: 4 }],
          }],
        },
        {
          id: 'remain_friends',
          text: '珍惜默契，不急着定义关系',
          preview: '增加人缘和心智，偏向长久友情',
          outcomes: [{
            id: 'friendship_remained',
            weight: 1,
            text: '热烈慢慢变成了长久的理解，你们仍会在重要时刻想起彼此。',
            effects: { charm: 1, intellect: 1 },
            addTags: ['lifelong_friend'],
            world: {
              relations: [{ id: 'friend', kind: 'friend', label: '故人', closenessDelta: 2 }],
              threads: [{ id: 'friendship', domain: 'relationship', label: '友情', intensity: 3 }],
            },
          }],
        },
        {
          id: 'step_back',
          text: '把心意留在自己这里',
          preview: '保护当下生活，但关系路线收窄',
          outcomes: [{
            id: 'guarded_heart',
            weight: 1,
            text: '生活没有因此失序，只是有些话从此留在了那个年纪。',
            effects: { intellect: 1 },
            addTags: ['guarded_heart'],
            world: {
              setFacts: { partnership: 'guarded' },
            },
          }],
        },
      ],
    },
    {
      id: 'side_project',
      minAge: 20,
      maxAge: 35,
      text: '下班后的一个小计划坚持了很久，终于有人愿意为成果付钱。',
      weight: 2,
      once: true,
      effects: { intellect: 1, wealth: 3, health: -1 },
      condition: { requiredMarks: { clarity: 2 } },
      addTags: ['built_something'],
    },
    {
      id: 'young_adult_year',
      minAge: 18,
      maxAge: 29,
      text: '生活由许多不起眼的工作日组成，你在其中慢慢站稳脚跟。',
      weight: 1,
      effects: { wealth: 1 },
    },
    {
      id: 'career_step',
      minAge: 27,
      maxAge: 45,
      text: '你接下了一项没人愿意负责的工作，完成后获得了新的位置。',
      weight: 3,
      once: true,
      effects: { wealth: 3, health: -1 },
      condition: { requiredTags: ['has_career'] },
      addTags: ['career_step'],
    },
    {
      id: 'unexpected_layoff',
      minAge: 28,
      maxAge: 52,
      text: '部门突然撤销。失去收入后，你必须决定下一步把力气放在哪里。',
      weight: 1,
      once: true,
      condition: { requiredTags: ['has_career'] },
      themes: ['career', 'learning', 'risk'],
      choices: [
        {
          id: 'seek_similar_work',
          text: '尽快寻找相似职位',
          preview: '减少家底，保留职业连续性',
          outcomes: [{
            id: 'slow_recovery',
            weight: 1,
            text: '过程比预计更久，但过去的经验最终帮你重新站稳。',
            effects: { wealth: -2, intellect: 1 },
            addTags: ['career_break', 'has_career'],
            world: {
              setFacts: { occupation: 'searching' },
              threads: [{ id: 'career_life', domain: 'career', label: '谋生', intensity: 5 }],
            },
            schedule: [{ eventId: 'career_turn', afterYears: 8, windowYears: 10 }],
          }],
        },
        {
          id: 'learn_again',
          text: '趁停下来重新学习',
          preview: '明显增加心智，损失时间、体魄和家底',
          outcomes: [{
            id: 'new_toolbox',
            weight: 1,
            text: '白天奔波，晚上学习，你慢慢拥有了另一套可以出发的工具。',
            effects: { intellect: 3, health: -1, wealth: -2 },
            addTags: ['career_break', 'kept_learning'],
            world: {
              setFacts: { occupation: 'searching', schooling: 'continued' },
              threads: [
                { id: 'career_life', domain: 'career', label: '谋生', intensity: 3 },
                { id: 'learning_mind', domain: 'learning', label: '再学一次', intensity: 3 },
              ],
            },
            schedule: [{ eventId: 'career_turn', afterYears: 8, windowYears: 10 }],
          }],
        },
        {
          id: 'try_own_business',
          text: '把积蓄押在自己的事情上',
          preview: '高风险，可能获得新的事业路线',
          condition: { requiredMarks: { means: 2 } },
          outcomes: [
            {
              id: 'venture_survived',
              weight: 2,
              text: '最难的几个月过去后，事情终于开始自己向前滚动。',
              effects: { wealth: 3, intellect: 2, health: -1 },
              addTags: ['career_break', 'built_something', 'second_career'],
              world: {
                setFacts: { occupation: 'venture' },
                threads: [{ id: 'career_life', domain: 'career', label: '自己的事', intensity: 5 }],
              },
            },
            {
              id: 'venture_failed',
              weight: 1,
              text: '积蓄几乎耗尽，但这次失败让你真正看懂了风险。',
              effects: { wealth: -4, intellect: 2 },
              addTags: ['career_break', 'early_failure'],
            },
          ],
        },
      ],
    },
    {
      id: 'make_a_home',
      minAge: 25,
      maxAge: 42,
      text: '你与重要的人走到需要共同决定未来的路口。',
      weight: 3,
      once: true,
      condition: { requiredTags: ['has_loved'] },
      themes: ['family', 'relationship'],
      choices: [
        {
          id: 'build_home_together',
          text: '认真组成一个家',
          preview: '增加人缘，承担长期经济责任',
          outcomes: [{
            id: 'shared_home',
            weight: 1,
            text: '从此许多计划里多了一个“我们”，也多了真实的责任。',
            effects: { charm: 3, wealth: -2 },
            addTags: ['made_a_home'],
            world: {
              setFacts: { partnership: 'home' },
              relations: [{ id: 'partner', kind: 'partner', label: '伴侣', closeness: 7 }],
              threads: [{ id: 'family_own', domain: 'family', label: '自己的家', intensity: 4 }],
            },
            schedule: [{ eventId: 'new_parent', afterYears: 2, windowYears: 4 }],
          }],
        },
        {
          id: 'keep_independence',
          text: '继续同行，但保留各自生活',
          preview: '心智和家底增加，家庭路线减弱',
          outcomes: [{
            id: 'parallel_lives',
            weight: 1,
            text: '你们没有照着常见答案生活，却找到了彼此都舒服的距离。',
            effects: { intellect: 1, wealth: 1 },
            addTags: ['independent_partnership'],
            world: {
              setFacts: { partnership: 'independent' },
              relations: [{ id: 'partner', kind: 'partner', label: '伴侣', closeness: 5 }],
            },
          }],
        },
        {
          id: 'part_kindly',
          text: '承认方向不同，认真告别',
          preview: '短期受伤，获得重新选择的空间',
          outcomes: [{
            id: 'kind_parting',
            weight: 1,
            text: '告别仍然难过，但你们没有把曾经的真心变成怨恨。',
            effects: { charm: 1, health: -1 },
            addTags: ['parted_kindly'],
            world: {
              setFacts: { partnership: 'parted' },
              relations: [{ id: 'partner', remove: true }],
              threads: [{ id: 'partnership', resolve: true }],
            },
          }],
        },
      ],
    },
    {
      id: 'new_parent',
      minAge: 27,
      maxAge: 45,
      text: '家中多了一个小小的新成员，时间与精力突然变得不够用。',
      weight: 2,
      once: true,
      condition: { requiredTags: ['made_a_home'] },
      themes: ['family', 'health', 'career'],
      choices: [
        {
          id: 'slow_down_career',
          text: '主动放慢工作节奏',
          preview: '增加家庭关系，减少家底',
          outcomes: [{
            id: 'present_parent',
            weight: 1,
            text: '收入增长慢了下来，但许多第一次你都没有错过。',
            effects: { charm: 3, wealth: -2 },
            addTags: ['raised_child', 'present_parent'],
            world: {
              setFacts: { parenting: 'child' },
              relations: [{ id: 'child', kind: 'child', label: '孩子', closeness: 7 }],
              threads: [
                { id: 'family_own', domain: 'family', label: '自己的家', intensity: 5 },
                { id: 'career_life', intensityDelta: -1 },
              ],
            },
          }],
        },
        {
          id: 'share_responsibility',
          text: '与家人重新分配责任',
          preview: '较均衡地承担健康与经济成本',
          outcomes: [{
            id: 'shared_parenting',
            weight: 1,
            text: '你们没有谁独自扛住一切，疲惫中仍保留了彼此。',
            effects: { charm: 2, health: -1, wealth: -1 },
            addTags: ['raised_child', 'shared_parenting'],
            world: {
              setFacts: { parenting: 'child' },
              relations: [
                { id: 'child', kind: 'child', label: '孩子', closeness: 6 },
                { id: 'partner', strainDelta: -1, closenessDelta: 1 },
              ],
            },
          }],
        },
        {
          id: 'ask_family_help',
          text: '接受前世灯火留下的帮助',
          preview: '以较小代价维持家庭关系',
          condition: { requiredCapabilityTags: ['family_support'] },
          outcomes: [{
            id: 'family_supported',
            weight: 1,
            text: '有人替你接住最疲惫的时刻，你也学会了不把求助当成失败。',
            effects: { charm: 3, wealth: -1 },
            addTags: ['raised_child', 'family_supported'],
            world: {
              setFacts: { parenting: 'child' },
              relations: [
                { id: 'child', kind: 'child', label: '孩子', closeness: 6 },
                { id: 'parents', closenessDelta: 1 },
              ],
            },
          }],
        },
      ],
    },
    {
      id: 'night_school',
      minAge: 30,
      maxAge: 50,
      text: '夜校招生的消息摆在面前，白天的生活却已经足够疲惫。',
      weight: 2,
      once: true,
      themes: ['learning', 'career', 'health'],
      choices: [
        {
          id: 'attend_night_school',
          text: '为自己留一盏夜灯',
          preview: '明显增加心智，消耗体魄和家底',
          outcomes: [{
            id: 'kept_attending',
            weight: 1,
            text: '白天已经很累，你仍一堂一堂坚持到了最后。',
            effects: { intellect: 3, health: -1, wealth: -1 },
            addTags: ['kept_learning'],
          }],
        },
        {
          id: 'rest_for_now',
          text: '承认现在需要休息',
          preview: '恢复体魄，也保留关系',
          outcomes: [{
            id: 'rested_without_shame',
            weight: 1,
            text: '你没有把暂停等同于放弃，生活重新有了一点余地。',
            effects: { health: 2, charm: 1 },
            addTags: ['chose_rest'],
          }],
        },
        {
          id: 'study_deeper',
          text: '循着前世的问题继续追究',
          preview: '获得更多心智，但付出更大健康成本',
          condition: { requiredCapabilityTags: ['learning_legacy'] },
          outcomes: [{
            id: 'deep_study',
            weight: 1,
            text: '有些问题像曾经问过，你比旁人更快找到了继续深入的方向。',
            effects: { intellect: 4, health: -2, wealth: -1 },
            addTags: ['kept_learning', 'deep_questions'],
          }],
        },
      ],
    },
    {
      id: 'lucky_contract',
      minAge: 25,
      maxAge: 48,
      text: '一次偶然认识的客户带来长期合作，你终于有了一点积蓄。',
      weight: 2,
      once: true,
      effects: { wealth: 4 },
      condition: { requiredTalentIds: ['lucky_pocket'] },
    },
    {
      id: 'adult_year',
      minAge: 30,
      maxAge: 49,
      text: '你在责任和日常之间维持平衡，账户与皱纹都多了一点。',
      weight: 1,
      effects: { wealth: 1 },
    },
    {
      id: 'health_warning',
      minAge: 42,
      maxAge: 65,
      text: '体检单上的箭头比往年多了，你需要决定是否真的改变生活。',
      weight: 3,
      once: true,
      themes: ['health', 'career'],
      choices: [
        {
          id: 'change_routine',
          text: '认真调整作息和习惯',
          preview: '恢复体魄，付出一些家底',
          outcomes: [{
            id: 'health_rebuilt',
            weight: 1,
            text: '改变很慢，但几个月后，身体终于给出了回应。',
            effects: { health: 3, wealth: -1 },
            addTags: ['health_warning', 'changed_habits'],
            world: {
              setFacts: { health: 'recovering' },
              threads: [{ id: 'health_watch', domain: 'health', label: '身体', intensity: 2 }],
            },
          }],
        },
        {
          id: 'keep_pushing',
          text: '先把眼前的事情做完',
          preview: '增加家底，明显损失体魄',
          outcomes: [{
            id: 'warning_ignored',
            weight: 1,
            text: '进度没有停下，身体却把每一次透支都记了下来。',
            effects: { wealth: 2, health: -3 },
            addTags: ['health_warning', 'ignored_warning'],
            world: {
              setFacts: { health: 'neglected' },
              threads: [{ id: 'health_watch', domain: 'health', label: '身体', intensity: 5 }],
            },
          }],
        },
        {
          id: 'seek_specialist',
          text: '花积蓄寻求更系统的帮助',
          preview: '消耗较多家底，大幅恢复体魄',
          condition: { requiredMarks: { means: 2 } },
          outcomes: [{
            id: 'treated_early',
            weight: 1,
            text: '问题被更早看见，也终于得到了一套真正可执行的方案。',
            effects: { health: 4, wealth: -3 },
            addTags: ['health_warning', 'treated_early'],
            world: {
              setFacts: { health: 'treated' },
              threads: [{ id: 'health_watch', domain: 'health', label: '身体', intensity: 1 }],
            },
          }],
        },
      ],
    },
    {
      id: 'old_friend_returns',
      minAge: 40,
      maxAge: 68,
      text: '多年未见的朋友从远方回来，你们发现沉默也能自然地接上。',
      weight: 2,
      once: true,
      effects: { charm: 2, health: 1 },
      condition: { requiredTags: ['lifelong_friend'] },
      domains: ['relationship'],
      world: {
        relations: [{ id: 'friend', kind: 'friend', label: '故人', closenessDelta: 2, strainDelta: -1 }],
      },
    },
    {
      id: 'career_turn',
      minAge: 43,
      maxAge: 62,
      text: '熟悉的岗位已经走到边缘，你开始衡量余下岁月还能怎样使用。',
      weight: 2,
      once: true,
      condition: { requiredMarks: { clarity: 2 } },
      themes: ['career', 'learning', 'legacy'],
      choices: [
        {
          id: 'stay_expert',
          text: '留在熟悉领域做到更深',
          preview: '稳定增加家底与心智',
          outcomes: [{
            id: 'deep_expertise',
            weight: 1,
            text: '你没有追逐新的名字，而是把多年经验磨成了真正的判断力。',
            effects: { intellect: 1, wealth: 2 },
            addTags: ['seasoned_expert'],
          }],
        },
        {
          id: 'change_field',
          text: '把经验带去一条新路',
          preview: '付出家底，开启第二事业',
          outcomes: [{
            id: 'second_career',
            weight: 1,
            text: '最初的不适过去后，你发现旧经验并没有浪费，只是换了语言。',
            effects: { intellect: 2, wealth: -1 },
            addTags: ['second_career'],
          }],
        },
        {
          id: 'mentor_others',
          text: '把位置让出来，开始带后来的人',
          preview: '增加人缘，打开传承路线',
          condition: { requiredTags: ['has_craft'] },
          outcomes: [{
            id: 'became_mentor',
            weight: 1,
            text: '当别人用自己的方式做成事情时，你第一次理解了传承。',
            effects: { charm: 2, intellect: 1 },
            addTags: ['passed_on_craft'],
            schedule: [{ eventId: 'community_class', afterYears: 10, windowYears: 8 }],
          }],
        },
      ],
    },
    {
      id: 'care_for_parents',
      minAge: 38,
      maxAge: 62,
      text: '父母开始需要你的照顾。你往返奔波，也重新认识了他们的年轻时代。',
      weight: 2,
      once: true,
      effects: { charm: 2, health: -1, wealth: -1 },
      addTags: ['cared_for_family'],
      domains: ['family', 'health'],
      world: {
        relations: [{ id: 'parents', closenessDelta: 2, strainDelta: 1 }],
        threads: [{ id: 'family_origin', domain: 'family', label: '原生家庭', intensity: 4 }],
      },
    },
    {
      id: 'middle_year',
      minAge: 50,
      maxAge: 64,
      text: '这一年没有大事，你学会把平静本身当作收获。',
      weight: 1,
      effects: { charm: 1 },
    },
    {
      id: 'late_bloom',
      minAge: 48,
      maxAge: 70,
      text: '一项坚持多年的本领终于被更多人看见，你迎来了迟到的高光。',
      weight: 4,
      unlockLevel: 6,
      once: true,
      effects: { intellect: 2, charm: 2, wealth: 3 },
      condition: { requiredTalentIds: ['late_bloomer'] },
      addTags: ['late_success'],
    },
    {
      id: 'retirement_day',
      minAge: 58,
      maxAge: 70,
      text: '退休的日期来到，你需要决定怎样安放突然空出来的时间。',
      weight: 4,
      once: true,
      themes: ['health', 'career', 'legacy'],
      choices: [
        {
          id: 'retire_fully',
          text: '彻底停下来，重新安排生活',
          preview: '恢复体魄，家底略有下降',
          outcomes: [{
            id: 'quiet_retirement',
            weight: 1,
            text: '没有闹钟的清晨起初陌生，后来渐渐有了自己的秩序。',
            effects: { health: 2, wealth: -1 },
            addTags: ['retired'],
            world: {
              setFacts: { occupation: 'retired' },
              threads: [{ id: 'career_life', resolve: true }],
            },
          }],
        },
        {
          id: 'work_part_time',
          text: '保留一部分熟悉的工作',
          preview: '继续增加家底，略微消耗体魄',
          outcomes: [{
            id: 'half_step_back',
            weight: 1,
            text: '你没有一下离开多年节奏，而是慢慢学会退到生活中央。',
            effects: { wealth: 1, health: -1 },
            addTags: ['semi_retired'],
            world: {
              setFacts: { occupation: 'semi_retired' },
              threads: [{ id: 'career_life', domain: 'career', label: '谋生', intensity: 2 }],
            },
          }],
        },
        {
          id: 'pass_experience',
          text: '把经验教给后来的人',
          preview: '增加人缘和心智，偏向传承路线',
          condition: { requiredTags: ['has_craft'] },
          outcomes: [{
            id: 'retired_mentor',
            weight: 1,
            text: '你收好旧物，却把最重要的诀窍留在了别人的手里。',
            effects: { charm: 2, intellect: 1 },
            addTags: ['retired', 'passed_on_craft'],
            world: {
              setFacts: { occupation: 'retired' },
              relations: [{ id: 'apprentice', kind: 'mentor', label: '后来的人', closeness: 4 }],
              threads: [
                { id: 'career_life', resolve: true },
                { id: 'craft_life', domain: 'craft', label: '手艺', intensity: 3 },
              ],
            },
          }],
        },
      ],
    },
    {
      id: 'community_class',
      minAge: 60,
      maxAge: 82,
      text: '你在社区教室分享自己的手艺，名字被一群年轻人记住。',
      weight: 2,
      once: true,
      effects: { charm: 2, intellect: 1 },
      condition: { requiredTags: ['has_craft'] },
      addTags: ['passed_on_craft'],
    },
    {
      id: 'long_trip',
      minAge: 60,
      maxAge: 78,
      text: '年轻时总说“以后再去”的地方仍在地图上，但身体和积蓄都不再年轻。',
      weight: 2,
      once: true,
      themes: ['travel', 'health'],
      choices: [
        {
          id: 'go_now',
          text: '现在就出发',
          preview: '消耗家底，增加体魄和人缘',
          outcomes: [{
            id: 'journey_kept',
            weight: 1,
            text: '路比记忆中更远，但抵达的那天，你庆幸没有再说一次以后。',
            effects: { charm: 2, wealth: -2, health: 1 },
            addTags: ['saw_far_places'],
          }],
        },
        {
          id: 'stay_close',
          text: '把远方换成附近的新路',
          preview: '稳妥恢复体魄并保留家底',
          outcomes: [{
            id: 'nearby_wonders',
            weight: 1,
            text: '你没有抵达地图另一端，却重新发现了生活半径里的陌生风景。',
            effects: { health: 1, wealth: 1 },
            addTags: ['found_nearby_world'],
          }],
        },
        {
          id: 'follow_old_memory',
          text: '循着前世记得的方向慢慢走',
          preview: '以较小代价完成远行',
          condition: { requiredCapabilityTags: ['travel_path'] },
          outcomes: [{
            id: 'remembered_road',
            weight: 1,
            text: '许多岔路明明第一次见，却让你产生一种久违的熟悉。',
            effects: { charm: 2, health: 1, wealth: -1 },
            addTags: ['saw_far_places', 'remembered_road'],
          }],
        },
      ],
    },
    {
      id: 'write_memories',
      minAge: 65,
      maxAge: 90,
      text: '旧照片铺满桌面，你开始思考这些故事应该留下些什么。',
      weight: 2,
      once: true,
      condition: { requiredMarks: { clarity: 3 } },
      themes: ['legacy', 'learning', 'family'],
      choices: [
        {
          id: 'write_for_family',
          text: '只写给亲近的人',
          preview: '增加心智和人缘，偏向家庭传承',
          outcomes: [{
            id: 'family_memories',
            weight: 1,
            text: '许多快要模糊的人和事重新有了名字，也有了愿意读下去的人。',
            effects: { intellect: 2, charm: 1 },
            addTags: ['wrote_memories', 'family_chronicle'],
          }],
        },
        {
          id: 'publish_memories',
          text: '整理成一本公开的书',
          preview: '消耗家底，明显增加人缘',
          outcomes: [{
            id: 'memories_shared',
            weight: 1,
            text: '陌生人的来信让你知道，一段普通人生也能照见另一个人。',
            effects: { intellect: 1, charm: 3, wealth: -1 },
            addTags: ['wrote_memories', 'published_memories'],
          }],
        },
        {
          id: 'read_between_lives',
          text: '辨认旧页背面反复出现的字',
          preview: '开启隐藏记忆与特殊结局线索',
          condition: { requiredCapabilityTags: ['hidden_memories'] },
          outcomes: [{
            id: 'hidden_story_revealed',
            weight: 1,
            text: '那些不属于本世的片段彼此接上，你第一次看见轮回留下的完整句子。',
            effects: { intellect: 3, charm: 2 },
            addTags: ['wrote_memories', 'revealed_hidden_story'],
          }],
        },
      ],
    },
    {
      id: 'grandchild_question',
      minAge: 58,
      maxAge: 85,
      text: '一个孩子认真问你年轻时是什么样。你讲着讲着，自己也笑了。',
      weight: 2,
      once: true,
      effects: { charm: 2, health: 1 },
      condition: { requiredTags: ['raised_child'] },
    },
    {
      id: 'senior_year',
      minAge: 65,
      maxAge: 79,
      text: '日子慢了下来。你更常散步，也更愿意与旧人通电话。',
      weight: 1,
      effects: { charm: 1 },
    },
    {
      id: 'old_photo',
      minAge: 78,
      maxAge: 99,
      text: '你在抽屉深处找到一张旧照片，照片里的人都还很年轻。',
      weight: 2,
      once: true,
      effects: { charm: 1, intellect: 1 },
    },
    {
      id: 'quiet_morning',
      minAge: 80,
      maxAge: 99,
      text: '你比太阳醒得更早，坐在窗前看城市一点点亮起来。',
      weight: 1,
      effects: {},
    },
    {
      id: 'hundredth_birthday',
      minAge: 100,
      maxAge: 100,
      text: '一百支蜡烛没有真的插上蛋糕，但所有人都记得这一刻。',
      weight: 10,
      once: true,
      effects: { charm: 2 },
      addTags: ['reached_century'],
      terminalReason: '你在百岁之后安静地走完了这一生。',
    },
    {
      id: 'work_home_clash',
      minAge: 28,
      maxAge: 50,
      text: '家里有人需要你留下的晚上，工作也卡在最后期限。两条线第一次真正互相挡住。',
      weight: 2,
      once: true,
      domains: ['career', 'family'],
      themes: ['career', 'family'],
      condition: {
        requiredTags: ['made_a_home'],
        anyTags: ['has_career', 'has_craft', 'built_something', 'second_career'],
      },
      couplings: [{
        minPressures: { career: 4, family: 4 },
        weightBonus: 8,
      }],
      choices: [
        {
          id: 'keep_deadline',
          text: '先把眼前的事做完',
          preview: '事业继续向前，家里会记住这次缺席',
          outcomes: [{
            id: 'deadline_kept',
            weight: 1,
            text: '任务完成了，可回家时灯已经关了。你开始明白有些错过补不回来。',
            effects: { wealth: 2, charm: -1, health: -1 },
            addTags: ['work_over_home'],
            world: {
              relations: [
                { id: 'partner', strainDelta: 2, closenessDelta: -1 },
                { id: 'child', strainDelta: 1 },
              ],
              threads: [{ id: 'career_life', domain: 'career', label: '谋生', intensityDelta: 1 }],
            },
          }],
        },
        {
          id: 'go_home_now',
          text: '放下工作回家',
          preview: '家庭更近，事业会松一截',
          outcomes: [{
            id: 'chose_the_door',
            weight: 1,
            text: '你赶到的时候，事情还没结束。有人因为你出现而放松下来。',
            effects: { charm: 2, wealth: -1 },
            addTags: ['home_over_work'],
            world: {
              relations: [
                { id: 'partner', closenessDelta: 1, strainDelta: -1 },
                { id: 'child', closenessDelta: 1 },
              ],
              threads: [{ id: 'career_life', intensityDelta: -1 }],
            },
          }],
        },
        {
          id: 'split_the_night',
          text: '把夜晚劈成两半硬扛',
          preview: '两边都顾一点，身体先付钱',
          outcomes: [{
            id: 'split_until_dawn',
            weight: 1,
            text: '你谁也没彻底辜负，只把自己耗到了天亮。',
            effects: { charm: 1, wealth: 1, health: -2 },
            addTags: ['split_too_thin'],
            world: {
              setFacts: { health: 'warning' },
              threads: [
                { id: 'family_own', intensityDelta: 1 },
                { id: 'career_life', intensityDelta: 1 },
              ],
            },
          }],
        },
      ],
    },
    {
      id: 'city_loneliness',
      minAge: 22,
      maxAge: 40,
      text: '城市很大，可这个周末没有人约你。你第一次看清：远行不只换了街道，也换了能说话的人。',
      weight: 2,
      once: true,
      domains: ['travel', 'relationship'],
      themes: ['travel', 'relationship'],
      condition: {
        requiredFacts: { residence: 'city' },
        forbiddenTags: ['made_a_home'],
      },
      couplings: [{
        allFacts: { residence: 'city' },
        minPressures: { relationship: 3 },
        weightBonus: 6,
      }],
      choices: [
        {
          id: 'join_strangers',
          text: '硬着头皮去认识新的人',
          preview: '人缘增加，城市开始有落点',
          outcomes: [{
            id: 'city_friends',
            weight: 1,
            text: '谈话起初客套，后来有人记住了你点的那杯东西。',
            effects: { charm: 2, wealth: -1 },
            addTags: ['city_community'],
            world: {
              relations: [{ id: 'friend', kind: 'friend', label: '新朋友', closeness: 4 }],
              threads: [{ id: 'city_life', domain: 'travel', label: '城市生活', intensity: 2 }],
            },
          }],
        },
        {
          id: 'call_home',
          text: '给故乡的人打电话',
          preview: '家人更近，自己仍在别处',
          outcomes: [{
            id: 'voice_from_home',
            weight: 1,
            text: '听筒里的嘈杂让你同时安心，也更想家。',
            effects: { charm: 1, intellect: 1 },
            addTags: ['called_home'],
            world: {
              relations: [{ id: 'parents', closenessDelta: 1 }],
            },
          }],
        },
        {
          id: 'keep_to_self',
          text: '把独处当成新的能力',
          preview: '心智增加，人情线变淡',
          outcomes: [{
            id: 'learned_solitude',
            weight: 1,
            text: '你没有急着填满晚上，却也把一些本来可能靠近的人放过去了。',
            effects: { intellect: 2, charm: -1 },
            addTags: ['chose_solitude'],
            world: {
              threads: [{ id: 'city_life', domain: 'travel', label: '城市生活', intensity: 3 }],
            },
          }],
        },
      ],
    },
    {
      id: 'body_keeps_score',
      minAge: 35,
      maxAge: 62,
      text: '事业还在向前，身体却在同一个星期里连续示警。你没法再假装这两件事互不相干。',
      weight: 2,
      once: true,
      domains: ['career', 'health'],
      themes: ['career', 'health'],
      condition: {
        anyTags: ['has_career', 'has_craft', 'built_something', 'second_career'],
        anyFacts: { health: ['warning', 'neglected', 'treated'] },
      },
      couplings: [{
        minPressures: { career: 4, health: 4 },
        weightBonus: 8,
      }],
      choices: [
        {
          id: 'cut_workload',
          text: '把工作往下卸一截',
          preview: '身体回升，家底放缓',
          outcomes: [{
            id: 'slowed_the_pace',
            weight: 1,
            text: '你少接了一截活。几个月后，睡眠比任何表扬都更像奖赏。',
            effects: { health: 3, wealth: -2 },
            addTags: ['chose_body'],
            world: {
              setFacts: { health: 'recovering' },
              threads: [
                { id: 'career_life', intensityDelta: -2 },
                { id: 'health_watch', domain: 'health', label: '身体', intensity: 2 },
              ],
            },
          }],
        },
        {
          id: 'push_through_pain',
          text: '先撑过这阵再谈休息',
          preview: '事业继续，身体记下这笔账',
          outcomes: [{
            id: 'pain_deferred',
            weight: 1,
            text: '事情是做成了。可你上下楼梯时，已经能听见身体在倒数。',
            effects: { wealth: 2, health: -3 },
            addTags: ['ignored_warning'],
            world: {
              setFacts: { health: 'neglected' },
              threads: [{ id: 'health_watch', domain: 'health', label: '身体', intensity: 6 }],
            },
          }],
        },
      ],
    },
    {
      id: 'friend_needs_you',
      minAge: 24,
      maxAge: 58,
      text: '多年的朋友忽然开口求助。你自己的日子也不宽裕，可这条线如果此刻松开，以后很难再接上。',
      weight: 2,
      once: true,
      domains: ['relationship', 'career'],
      themes: ['relationship', 'career'],
      condition: { requiredRelations: ['friend'] },
      couplings: [{
        allRelations: ['friend'],
        minPressures: { relationship: 4 },
        weightBonus: 6,
      }],
      choices: [
        {
          id: 'help_the_friend',
          text: '把能挪的都挪过去',
          preview: '友情加深，家底减少',
          outcomes: [{
            id: 'friend_held',
            weight: 1,
            text: '你帮得并不轻松，但对方后来把这件事记得比你更清楚。',
            effects: { charm: 3, wealth: -2 },
            addTags: ['kept_a_friend'],
            world: {
              relations: [{ id: 'friend', closenessDelta: 2, strainDelta: -1 }],
            },
          }],
        },
        {
          id: 'help_within_limit',
          text: '帮一点，也说明自己的限度',
          preview: '关系仍在，双方都更明白边界',
          outcomes: [{
            id: 'honest_limit',
            weight: 1,
            text: '话有点难说，可说完之后，你们都还站在原地。',
            effects: { charm: 1, intellect: 1, wealth: -1 },
            addTags: ['honest_friendship'],
            world: {
              relations: [{ id: 'friend', closenessDelta: 1 }],
            },
          }],
        },
        {
          id: 'cannot_help_now',
          text: '承认这次帮不上',
          preview: '保住当下生活，友情会冷一截',
          outcomes: [{
            id: 'friend_let_go',
            weight: 1,
            text: '对方没有骂你。只是此后问候变得更短，间隔变得更长。',
            effects: { intellect: 1, charm: -2 },
            addTags: ['lost_a_chance'],
            world: {
              relations: [{ id: 'friend', closenessDelta: -2, strainDelta: 1 }],
            },
          }],
        },
      ],
    },
    {
      id: 'parents_far_away',
      minAge: 30,
      maxAge: 58,
      text: '故乡的电话打来时，你正在另一座城市赶下一件事。父母的需要和工作的节奏叠在了同一周。',
      weight: 2,
      once: true,
      domains: ['family', 'travel', 'career'],
      themes: ['family', 'travel'],
      condition: {
        requiredFacts: { residence: 'city' },
        requiredRelations: ['parents'],
      },
      couplings: [{
        allFacts: { residence: 'city' },
        allRelations: ['parents'],
        minPressures: { family: 4 },
        weightBonus: 7,
      }],
      choices: [
        {
          id: 'go_back_often',
          text: '把往返当成新的日常',
          preview: '家人更近，体魄和家底都要付账',
          outcomes: [{
            id: 'commuting_home',
            weight: 1,
            text: '车站比办公室更熟悉了。你少了一些升迁，多看见了父母还没说出口的老。',
            effects: { charm: 2, health: -1, wealth: -2 },
            addTags: ['cared_for_family'],
            world: {
              relations: [{ id: 'parents', closenessDelta: 2 }],
              threads: [{ id: 'family_origin', domain: 'family', label: '原生家庭', intensity: 4 }],
            },
          }],
        },
        {
          id: 'send_money_home',
          text: '用积蓄把照顾托付给当地',
          preview: '花钱换安心，自己仍隔着距离',
          outcomes: [{
            id: 'care_from_afar',
            weight: 1,
            text: '账单按时寄出，电话里的声音稳了一些。你知道这不是陪伴，只是你此刻能给的。',
            effects: { wealth: -3, charm: 1 },
            addTags: ['supported_from_afar'],
            world: {
              relations: [{ id: 'parents', strainDelta: -1 }],
            },
          }],
        },
        {
          id: 'delay_the_visit',
          text: '等手头这阵过去再回去',
          preview: '事业不被打断，亲情会记账',
          outcomes: [{
            id: 'later_and_later',
            weight: 1,
            text: '后来你回去了。只是有些话已经没有原来那个听的人了。',
            effects: { wealth: 1, charm: -2 },
            addTags: ['delayed_home'],
            world: {
              relations: [{ id: 'parents', closenessDelta: -2, strainDelta: 2 }],
            },
          }],
        },
      ],
    },
    {
      id: 'restless_hometown',
      minAge: 28,
      maxAge: 46,
      text: '你把根留在熟悉的街上，可偶尔仍会梦见没去成的那列夜车。安稳和未走的路开始互相提问。',
      weight: 2,
      once: true,
      domains: ['family', 'travel'],
      themes: ['family', 'travel'],
      condition: {
        requiredTags: ['stayed_hometown'],
        forbiddenTags: ['left_hometown'],
      },
      couplings: [{
        allFacts: { residence: 'hometown' },
        minPressures: { family: 3, travel: 2 },
        weightBonus: 5,
      }],
      choices: [
        {
          id: 'leave_late',
          text: '现在出发也不算晚',
          preview: '换一座城，故乡的关系会拉开',
          outcomes: [{
            id: 'late_departure',
            weight: 1,
            text: '行李比年轻时更重，决心却更清楚。你走的时候，有人来送。',
            effects: { intellect: 2, charm: 1, wealth: -2 },
            addTags: ['left_hometown', 'late_traveler'],
            world: {
              setFacts: { residence: 'city' },
              threads: [{ id: 'city_life', domain: 'travel', label: '城市生活', intensity: 3 }],
            },
          }],
        },
        {
          id: 'stay_and_deepen',
          text: '把没走的路活成选择而不是遗憾',
          preview: '本地关系更深，心安下来',
          outcomes: [{
            id: 'roots_chosen',
            weight: 1,
            text: '你停止把留下写成失败。这条街因为你认真对待，也开始认真对待你。',
            effects: { charm: 2, health: 1 },
            addTags: ['local_anchor'],
            world: {
              relations: [{ id: 'parents', closenessDelta: 1 }],
              threads: [{ id: 'family_origin', domain: 'family', label: '原生家庭', intensity: 3 }],
            },
          }],
        },
      ],
    },
  ],

  endings: [
    {
      id: 'century_witness',
      title: '百年见证者',
      description: '一个世纪从你眼前经过，而你把故事留给了后来的人。',
      priority: 100,
      minAge: 100,
    },
    {
      id: 'keeper_between_lives',
      title: '轮回拾页人',
      description: '你在旧日文字间认出了不属于这一世的回声，并把它带回轮回深处。',
      priority: 95,
      minAge: 65,
      requiredTags: ['revealed_hidden_story'],
    },
    {
      id: 'late_light',
      title: '迟来的光',
      description: '你没有急着证明自己，却在漫长岁月里活成了独特的答案。',
      priority: 90,
      minAge: 65,
      requiredTags: ['late_success'],
    },
    {
      id: 'life_of_learning',
      title: '求知一生',
      description: '世界越大，你越清楚自己不知道什么，于是一直没有停止学习。',
      priority: 80,
      minAge: 65,
      requiredMarks: { clarity: 3 },
    },
    {
      id: 'full_house',
      title: '灯火有人等',
      description: '你留下的不是耀眼履历，而是一桌总有人赴约的饭。',
      priority: 80,
      minAge: 65,
      requiredMarks: { presence: 3 },
      requiredTags: ['made_a_home'],
    },
    {
      id: 'earned_freedom',
      title: '从容余生',
      description: '多年的经营换来选择生活方式的自由，你终于不再被账单催促。',
      priority: 75,
      minAge: 65,
      requiredMarks: { means: 3 },
    },
    {
      id: 'long_road',
      title: '长路有痕',
      description: '没有传奇降临，但你认真走过的每一年都留下了痕迹。',
      priority: 60,
      minAge: 80,
    },
    {
      id: 'young_comet',
      title: '未落款的序章',
      description: '故事停在很早的地方，许多可能尚未来得及拥有名字。',
      priority: 50,
      maxAge: 17,
    },
    {
      id: 'unfinished_path',
      title: '行至半途',
      description: '你已经走出自己的方向，只是这一世没有足够时间抵达。',
      priority: 40,
      maxAge: 44,
    },
    {
      id: 'ordinary_days',
      title: '人间寻常',
      description: '喜怒得失交替出现，你度过了一段普通而完整的人生。',
      priority: 0,
    },
  ],
};
