import { HistoryFigure, HistoryRegion } from '../core/model';

export const HISTORY_REGIONS: HistoryRegion[] = [
  {
    id: 'china-ancient',
    name: '华夏古典',
    era: '古 · 中',
    description: '问礼、入仕、流放与江海。你走在已经被无数次讲述过的路上。',
  },
  {
    id: 'china-modern',
    name: '华夏近现代',
    era: '今 · 中',
    description: '学堂、铁路、报刊与革命。许多路是第一次被走出来。',
  },
  {
    id: 'west-ancient',
    name: '西洋古典',
    era: '古 · 外',
    description: '广场、军团、工坊与神庙。城邦把个人的一生当成公共事务。',
  },
  {
    id: 'west-modern',
    name: '西洋近现代',
    era: '今 · 外',
    description: '实验室、议会、画布与战场。一个人的选择会写进更大的世纪。',
  },
];

export const HISTORY_FIGURES: HistoryFigure[] = [
  {
    id: 'kongzi',
    name: '孔丘',
    region: 'china-ancient',
    epithet: '问礼的人',
    opening: '这一世，你走在鲁国那个曾经问礼的人走过的路上。没有人要求你成为他，只是路已经在那里。',
    grantMarks: [{ id: 'clarity', intensity: 2 }, { id: 'presence', intensity: 1 }],
    chapters: [
      { scenarioId: 'childhood', title: '问礼', intro: '太庙里的器物你都要问一遍。有人嫌烦，你觉得不问才荒唐。', years: 16 },
      { scenarioId: 'studies', title: '杏坛', intro: '学生比俸禄来得更早。你把问题当作食粮。', years: 18 },
      { scenarioId: 'journey', title: '周游', intro: '列国的门开了又关。你仍把车辙当成教材。', years: 14 },
      { scenarioId: 'dusk', title: '诗书', intro: '有些话必须写下，否则下一代只会记住热闹。', years: 16 },
    ],
  },
  {
    id: 'libai',
    name: '李白',
    region: 'china-ancient',
    epithet: '仗剑的人',
    opening: '这一世，酒、月和远路会反复来找你。你仍要自己决定走哪一条。',
    grantMarks: [{ id: 'presence', intensity: 2 }, { id: 'lucky', intensity: 1 }],
    chapters: [
      { scenarioId: 'journey', title: '仗剑去国', intro: '你把故乡留在身后，像把剑横在膝上。' },
      { scenarioId: 'service', title: '翰林', intro: '宫里要你写的是颂，你想写的是风。' },
      { scenarioId: 'journey', title: '放还', intro: '金子是送客的礼。江比朝堂宽。' },
      { scenarioId: 'dusk', title: '捉月', intro: '水里的月亮比岸上的更像你认识的那种。' },
    ],
  },
  {
    id: 'sushi',
    name: '苏轼',
    region: 'china-ancient',
    epithet: '被贬仍唱的人',
    opening: '这一世你会经过考场、台谏和黄州的雨。路不由你选起点，过程仍由你写。',
    grantMarks: [{ id: 'clarity', intensity: 2 }, { id: 'vitality', intensity: 1 }],
    chapters: [
      { scenarioId: 'studies', title: '科举', intro: '文章是门票。你真正想问的不在卷面上。' },
      { scenarioId: 'service', title: '朝堂', intro: '话多了会得罪人。你还是把该说的说了。' },
      { scenarioId: 'journey', title: '黄州', intro: '贬谪把日子变慢。东坡的名字是后来才有的。' },
      { scenarioId: 'dusk', title: '惠州与儋州', intro: '再远一点，海都进来了。你仍在给朋友写信。' },
    ],
  },
  {
    id: 'qiujin',
    name: '秋瑾',
    region: 'china-modern',
    epithet: '东渡的人',
    opening: '这一世，刀、诗和学堂会同时出现。你要决定哪一样先下手。',
    grantMarks: [{ id: 'sturdy', intensity: 2 }, { id: 'presence', intensity: 1 }],
    chapters: [
      { scenarioId: 'journey', title: '东渡', intro: '海比家训更宽。你在船上把头发盘紧。' },
      { scenarioId: 'studies', title: '办学', intro: '教室是另一种战场。笔和枪都要会。' },
      { scenarioId: 'service', title: '起事', intro: '消息走漏的那天，路只剩下向前。' },
      { scenarioId: 'dusk', title: '轩亭', intro: '名字会被后来的人反复念。那不是你当时想的事。' },
    ],
  },
  {
    id: 'luxun',
    name: '周树人',
    region: 'china-modern',
    epithet: '弃医从文的人',
    opening: '这一世你会看见病，也会看见比病更深的麻木。你要决定救哪一层。',
    grantMarks: [{ id: 'clarity', intensity: 2 }, { id: 'isolation', intensity: 1 }],
    chapters: [
      { scenarioId: 'studies', title: '学医', intro: '解剖室很安静。你以为痛可以被切开。' },
      { scenarioId: 'journey', title: '幻灯', intro: '银幕上的人群让你把手术刀放下。' },
      { scenarioId: 'craft', title: '呐喊', intro: '文章是另一把刀。你写得很慢，也很准。' },
      { scenarioId: 'dusk', title: '横眉', intro: '有人要你宽容。你把这句话也写进了书里。' },
    ],
  },
  {
    id: 'zhantianyou',
    name: '詹天佑',
    region: 'china-modern',
    epithet: '把路修过山的人',
    opening: '这一世，铁、测量和别人的怀疑会排成一队。你用完成来回答。',
    grantMarks: [{ id: 'clarity', intensity: 1 }, { id: 'tools', intensity: 2 }],
    chapters: [
      { scenarioId: 'studies', title: '留美', intro: '语言和公式一起进来。你把两者都学到能用。' },
      { scenarioId: 'craft', title: '铁路', intro: '别人说这山过不去。你把尺子往上移。' },
      { scenarioId: 'service', title: '京张', intro: '通车那天，汽笛比贺词更像结论。' },
      { scenarioId: 'dusk', title: '图纸', intro: '你留下的不是传说，是还能再修一次的方法。' },
    ],
  },
  {
    id: 'socrates',
    name: '苏格拉底',
    region: 'west-ancient',
    epithet: '在街上提问的人',
    opening: '这一世，雅典的广场会把你的问题变成公共事件。你仍可以选择沉默。',
    grantMarks: [{ id: 'clarity', intensity: 3 }],
    chapters: [
      { scenarioId: 'childhood', title: '石匠之子', intro: '石头有纹路。人的话也有。' },
      { scenarioId: 'studies', title: '诘问', intro: '你不收学费。你收的是对方的确定。' },
      { scenarioId: 'service', title: '申辩', intro: '法庭要你认错。你把问题又问了一遍。' },
      { scenarioId: 'dusk', title: '饮鸩', intro: '朋友要你逃。你说城邦的法也是你的老师。' },
    ],
  },
  {
    id: 'caesar',
    name: '恺撒',
    region: 'west-ancient',
    epithet: '过河的人',
    opening: '这一世，军团、债务和元老院会同时催你。河就在前面。',
    grantMarks: [{ id: 'presence', intensity: 2 }, { id: 'job', intensity: 1 }],
    chapters: [
      { scenarioId: 'service', title: '财务官', intro: '罗马要你先会花钱，再会打仗。' },
      { scenarioId: 'journey', title: '高卢', intro: '远征把你的名字送回城里。城比战场更危险。' },
      { scenarioId: 'service', title: '卢比孔', intro: '过河没有回头。骰子是你自己掷的。' },
      { scenarioId: 'dusk', title: '三月十五', intro: '身边站着你认识的人。这是最难的一种意外。' },
    ],
  },
  {
    id: 'vinci',
    name: '达·芬奇',
    region: 'west-ancient',
    epithet: '什么都想拆开的人',
    opening: '这一世，画、机械和人体会争夺同一双手。你很难只做一件事。',
    grantMarks: [{ id: 'clarity', intensity: 2 }, { id: 'tools', intensity: 1 }],
    chapters: [
      { scenarioId: 'craft', title: '工坊', intro: '颜料和齿轮放在同一张桌上。师傅皱眉。' },
      { scenarioId: 'service', title: '米兰', intro: '公爵要你画，也要你设计战争。' },
      { scenarioId: 'studies', title: '笔记', intro: '你把看见的都记下来，包括还不会做的。' },
      { scenarioId: 'dusk', title: '未完成', intro: '许多稿停在最好的那一笔之前。这并不使它们变小。' },
    ],
  },
  {
    id: 'curie',
    name: '居里',
    region: 'west-modern',
    epithet: '在棚屋里提纯的人',
    opening: '这一世，寒冷、辐射和两个国家的名字会同时跟着你。实验室比礼堂更真实。',
    grantMarks: [{ id: 'clarity', intensity: 2 }, { id: 'sturdy', intensity: 1 }],
    chapters: [
      { scenarioId: 'studies', title: '索邦', intro: '座位在后排。公式在最前面。' },
      { scenarioId: 'craft', title: '棚屋', intro: '吨计的矿渣里，有一点点新的东西。' },
      { scenarioId: 'service', title: '两次承认', intro: '奖来了。你把它当成继续做的许可证。' },
      { scenarioId: 'dusk', title: '手', intro: '手被工作改变了形状。笔记本还在发光。' },
    ],
  },
  {
    id: 'lincoln',
    name: '林肯',
    region: 'west-modern',
    epithet: '把话说完整的人',
    opening: '这一世，法庭、分裂的国家和一篇很短的讲演会等着你。你先得学会把句子说完。',
    grantMarks: [{ id: 'presence', intensity: 2 }, { id: 'clarity', intensity: 1 }],
    chapters: [
      { scenarioId: 'studies', title: '自学', intro: '书是借来的。道理要自己走一遍。' },
      { scenarioId: 'service', title: '律师', intro: '你替人说话，也慢慢学会替一个更大的“我们”说话。' },
      { scenarioId: 'service', title: '分裂', intro: '国家要你选择完整还是安静。安静更便宜。' },
      { scenarioId: 'dusk', title: '剧院', intro: '战争停了。有些子弹还没有停。' },
    ],
  },
  {
    id: 'vangogh',
    name: '梵高',
    region: 'west-modern',
    epithet: '把颜色用尽的人',
    opening: '这一世，矿区、阿尔的太阳和一封没寄出的信会反复出现。卖不掉并不等于没看见。',
    grantMarks: [{ id: 'presence', intensity: 1 }, { id: 'wear', intensity: 1 }],
    chapters: [
      { scenarioId: 'service', title: '矿区', intro: '你想救人。人们要的是煤。' },
      { scenarioId: 'journey', title: '阿尔', intro: '光太强了。你决定把它留下。' },
      { scenarioId: 'craft', title: '向日葵', intro: '同一盆花你画了很多次。每一次都更像你看见的。' },
      { scenarioId: 'dusk', title: '麦田', intro: '乌鸦比画商更早来。你把最后的黄用完了。' },
    ],
  },
];
