import { LegacyConfig } from '../core/model';

export const LEGACIES: LegacyConfig[] = [
  {
    id: 'memory_of_abundance',
    name: '余裕之忆',
    description: '装备后，每世开局带着「开局余裕」，起步少一点紧巴。',
    category: 'origin',
    persistence: 'permanent',
    unlockLevel: 1,
    maxRank: 2,
    effect: { type: 'starting-points', amount: 1 },
  },
  {
    id: 'many_possible_selves',
    name: '万千可能',
    description: '装备后，开局天赋候选数量 +1。',
    category: 'origin',
    persistence: 'permanent',
    unlockLevel: 3,
    maxRank: 2,
    effect: { type: 'talent-candidates', amount: 1 },
  },
  {
    id: 'turn_back_time',
    name: '回眸一刻',
    description: '装备后，每世可改写一次尚未选择的关键遭遇。',
    category: 'fate',
    persistence: 'permanent',
    unlockLevel: 1,
    maxRank: 2,
    effect: { type: 'event-reroll', charges: 1 },
  },
  {
    id: 'clear_omens',
    name: '看见征兆',
    description: '装备后，可以看见每个选择会留下什么光环、行囊或负累。',
    category: 'fate',
    persistence: 'permanent',
    unlockLevel: 2,
    maxRank: 1,
    effect: { type: 'choice-foresight', detail: 'range' },
  },
  {
    id: 'borrowed_breath',
    name: '借来的一口气',
    description: '装备后，每世第一次撑不住时，会压下「透支」，让你再留一口气。',
    category: 'fate',
    persistence: 'permanent',
    unlockLevel: 4,
    maxRank: 1,
    effect: { type: 'death-guard', charges: 1 },
    condition: { maxAge: 49 },
  },
  {
    id: 'book_of_questions',
    name: '未问完的问题',
    description: '装备后，在学习事件中解锁“追根究底”类选项。',
    category: 'path',
    persistence: 'permanent',
    unlockLevel: 1,
    maxRank: 1,
    effect: { type: 'unlock-choice-tag', tag: 'learning_legacy' },
    condition: { anyTags: ['loves_stories', 'library_regular', 'kept_learning'] },
  },
  {
    id: 'craft_in_hands',
    name: '手上的记忆',
    description: '装备后，在工作与传承事件中解锁手艺路线选项。',
    category: 'path',
    persistence: 'permanent',
    unlockLevel: 1,
    maxRank: 1,
    effect: { type: 'unlock-choice-tag', tag: 'craft_legacy' },
    condition: { anyTags: ['has_craft', 'passed_on_craft'] },
  },
  {
    id: 'warm_lights',
    name: '灯火长明',
    description: '装备后，在家庭事件中解锁“接受家人帮助”类选项。',
    category: 'path',
    persistence: 'permanent',
    unlockLevel: 2,
    maxRank: 1,
    effect: { type: 'unlock-choice-tag', tag: 'family_support' },
    condition: { anyTags: ['made_a_home', 'raised_child', 'cared_for_family'] },
  },
  {
    id: 'far_horizons',
    name: '远方仍在',
    description: '装备后，在人生路口解锁部分远行选项。',
    category: 'path',
    persistence: 'permanent',
    unlockLevel: 2,
    maxRank: 1,
    effect: { type: 'unlock-choice-tag', tag: 'travel_path' },
    condition: { anyTags: ['left_hometown', 'saw_far_places', 'many_hometowns'] },
  },
  {
    id: 'begin_again',
    name: '再起之心',
    description: '装备后，职业转型事件更容易出现。',
    category: 'path',
    persistence: 'permanent',
    unlockLevel: 3,
    maxRank: 1,
    effect: { type: 'event-theme-boost', theme: 'career' },
    condition: { anyTags: ['career_break', 'second_career', 'built_something'] },
  },
  {
    id: 'hidden_echoes',
    name: '旧页背面的字',
    description: '装备后，解锁隐藏记忆选项与对应结局线索。',
    category: 'story',
    persistence: 'permanent',
    unlockLevel: 4,
    maxRank: 1,
    effect: { type: 'unlock-content-tag', tag: 'hidden_memories' },
    condition: { anyTags: ['wrote_memories', 'reached_century'] },
  },
  {
    id: 'body_remembers',
    name: '身体记得路',
    description: '装备后，健康事件更容易出现。',
    category: 'path',
    persistence: 'permanent',
    unlockLevel: 3,
    maxRank: 1,
    effect: { type: 'event-theme-boost', theme: 'health' },
    condition: { anyTags: ['health_warning', 'reached_century'] },
  },
  {
    id: 'gentle_next_dawn',
    name: '下世微光',
    description: '只在下一世生效：第一次负面属性变化各减轻 1 点。',
    category: 'boon',
    persistence: 'next-life',
    unlockLevel: 1,
    maxRank: 1,
    effect: { type: 'negative-shield', charges: 1 },
  },
  {
    id: 'full_pockets_next_time',
    name: '下世余粮',
    description: '只在下一世生效：开局带着更厚的余粮。',
    category: 'boon',
    persistence: 'next-life',
    unlockLevel: 1,
    maxRank: 1,
    effect: { type: 'starting-points', amount: 2 },
  },
  {
    id: 'favorable_wind',
    name: '下世顺风',
    description: '只在下一世生效：可改写两次关键遭遇。',
    category: 'boon',
    persistence: 'next-life',
    unlockLevel: 2,
    maxRank: 1,
    effect: { type: 'event-reroll', charges: 2 },
  },
];
