import { LifeStageConfig } from '../core/model';

export const LIFE_STAGES: LifeStageConfig[] = [
  {
    id: 'childhood',
    name: '童年',
    minAge: 0,
    maxAge: 11,
    focuses: [
      {
        id: 'child_curiosity',
        name: '追着问题长大',
        description: '更容易遇见启蒙与学习经历，心智 +1。',
        effects: { intellect: 1 },
        preferredThemes: ['learning'],
      },
      {
        id: 'child_companions',
        name: '和伙伴混在一起',
        description: '更容易遇见友情与家庭经历，人缘 +1。',
        effects: { charm: 1 },
        preferredThemes: ['relationship', 'family'],
      },
      {
        id: 'child_outdoors',
        name: '在风里跑大',
        description: '更容易遇见运动与健康经历，体魄 +1。',
        effects: { health: 1 },
        preferredThemes: ['health', 'travel'],
      },
    ],
  },
  {
    id: 'teenage',
    name: '少年',
    minAge: 12,
    maxAge: 17,
    focuses: [
      {
        id: 'teen_study',
        name: '认真读书',
        description: '学业相关机会增加，心智 +1。',
        effects: { intellect: 1 },
        preferredThemes: ['learning'],
      },
      {
        id: 'teen_friends',
        name: '珍惜同伴',
        description: '友情与关系事件增加，人缘 +1。',
        effects: { charm: 1 },
        preferredThemes: ['relationship'],
      },
      {
        id: 'teen_skills',
        name: '先学一门本事',
        description: '技能和工作路线机会增加，家底 +1。',
        effects: { wealth: 1 },
        preferredThemes: ['craft', 'career'],
        capabilityTags: ['practical_path'],
      },
    ],
  },
  {
    id: 'youth',
    name: '青年',
    minAge: 18,
    maxAge: 29,
    focuses: [
      {
        id: 'youth_stability',
        name: '先站稳脚跟',
        description: '稳定职业与积累事件增加，家底 +1。',
        effects: { wealth: 1 },
        preferredThemes: ['career', 'family'],
      },
      {
        id: 'youth_horizon',
        name: '去更远的地方',
        description: '远行和新环境事件增加，心智 +1。',
        effects: { intellect: 1 },
        preferredThemes: ['travel', 'learning'],
        capabilityTags: ['travel_path'],
      },
      {
        id: 'youth_bold',
        name: '赌一次可能',
        description: '高风险机会增加，人缘 +1。',
        effects: { charm: 1 },
        preferredThemes: ['career', 'risk'],
        capabilityTags: ['bold_path'],
      },
    ],
  },
  {
    id: 'adulthood',
    name: '壮年',
    minAge: 30,
    maxAge: 49,
    focuses: [
      {
        id: 'adult_career',
        name: '把事业做深',
        description: '职业和创造事件增加，家底 +1。',
        effects: { wealth: 1 },
        preferredThemes: ['career', 'craft'],
      },
      {
        id: 'adult_family',
        name: '把灯火守好',
        description: '家庭和关系事件增加，人缘 +1。',
        effects: { charm: 1 },
        preferredThemes: ['family', 'relationship'],
      },
      {
        id: 'adult_self',
        name: '为自己留一条路',
        description: '学习和转型事件增加，心智 +1。',
        effects: { intellect: 1 },
        preferredThemes: ['learning', 'career'],
        capabilityTags: ['reinvention_path'],
      },
    ],
  },
  {
    id: 'midlife',
    name: '中年',
    minAge: 50,
    maxAge: 64,
    focuses: [
      {
        id: 'midlife_health',
        name: '先照顾身体',
        description: '健康与休息事件增加，体魄 +1。',
        effects: { health: 1 },
        preferredThemes: ['health'],
      },
      {
        id: 'midlife_change',
        name: '再改变一次',
        description: '转型和学习事件增加，心智 +1。',
        effects: { intellect: 1 },
        preferredThemes: ['career', 'learning', 'travel'],
        capabilityTags: ['reinvention_path'],
      },
      {
        id: 'midlife_care',
        name: '照顾重要的人',
        description: '家庭与关系事件增加，人缘 +1。',
        effects: { charm: 1 },
        preferredThemes: ['family', 'relationship'],
      },
    ],
  },
  {
    id: 'later_years',
    name: '晚年',
    minAge: 65,
    maxAge: 100,
    focuses: [
      {
        id: 'later_legacy',
        name: '留下些什么',
        description: '传承和回忆事件增加，心智 +1。',
        effects: { intellect: 1 },
        preferredThemes: ['legacy', 'learning'],
      },
      {
        id: 'later_explore',
        name: '继续看看世界',
        description: '远行和新鲜经历增加，人缘 +1。',
        effects: { charm: 1 },
        preferredThemes: ['travel', 'relationship'],
        capabilityTags: ['travel_path'],
      },
      {
        id: 'later_peace',
        name: '安稳地过日子',
        description: '健康和平静事件增加，体魄 +1。',
        effects: { health: 1 },
        preferredThemes: ['health', 'family'],
      },
    ],
  },
];
