import { MarkDef } from '../core/model';

export const MARKS: MarkDef[] = [
  {
    id: 'vitality',
    slot: 'body',
    nature: 'aura',
    ranks: ['气色回了', '筋骨结实', '体气充沛'],
    hint: '身体这条线更常走向恢复，也更不容易被岁月一下子收走。',
    boostDomains: ['health'],
    mortality: -0.012,
    kindBias: 0.2,
  },
  {
    id: 'wear',
    slot: 'body',
    nature: 'burden',
    ranks: ['有点乏', '透支', '快撑不住'],
    hint: '疲惫会把不利的身体结果推到更近的地方。',
    boostDomains: ['health'],
    mortality: 0.02,
    harshBias: 0.35,
  },
  {
    id: 'sturdy',
    slot: 'body',
    nature: 'aura',
    ranks: ['少生病', '耐折腾', '很难被打垮'],
    hint: '同样的风险里，你更常留下。',
    boostDomains: ['health'],
    mortality: -0.018,
    kindBias: 0.15,
  },
  {
    id: 'clarity',
    slot: 'mind',
    nature: 'aura',
    ranks: ['开了窍', '见识渐长', '问得深'],
    hint: '求知与转型的机会更容易找上门，好的结果也更站得住。',
    boostDomains: ['learning'],
    kindBias: 0.25,
  },
  {
    id: 'presence',
    slot: 'bond',
    nature: 'aura',
    ranks: ['面善', '有人愿意信你', '众望所归'],
    hint: '人情事件更常出现，关系也更容易向好处偏。',
    boostDomains: ['relationship', 'family'],
    kindBias: 0.2,
  },
  {
    id: 'isolation',
    slot: 'bond',
    nature: 'burden',
    ranks: ['话少了', '一个人过', '门庭冷清'],
    hint: '独处会把关系里的冷结果放大。',
    boostDomains: ['relationship'],
    harshBias: 0.25,
  },
  {
    id: 'means',
    slot: 'means',
    nature: 'possession',
    ranks: ['刚够花', '手头宽裕', '进退有余'],
    hint: '生计更稳，也更有本钱去赌一次。',
    boostDomains: ['career'],
    kindBias: 0.2,
  },
  {
    id: 'want',
    slot: 'means',
    nature: 'burden',
    ranks: ['紧巴', '捉襟见肘', '掏空了'],
    hint: '缺钱时，损失类结果更容易成真。',
    boostDomains: ['career'],
    harshBias: 0.3,
  },
  {
    id: 'savings',
    slot: 'means',
    nature: 'possession',
    ranks: ['会留一点', '有余钱', '家底厚实'],
    hint: '你更常把钱变成退路，而不是花完再想。',
    boostDomains: ['career'],
    kindBias: 0.15,
  },
  {
    id: 'tools',
    slot: 'means',
    nature: 'possession',
    ranks: ['有手艺', '家伙齐', '一门安身的本事'],
    hint: '手艺路线更常出现，也更站得住。',
    boostDomains: ['craft', 'career'],
    kindBias: 0.2,
  },
  {
    id: 'job',
    slot: 'means',
    nature: 'possession',
    ranks: ['有工牌', '站稳了', '位置还在'],
    hint: '职业线索更重，稳定的结果更常见。',
    boostDomains: ['career'],
  },
  {
    id: 'lucky',
    slot: 'means',
    nature: 'aura',
    ranks: ['偶有转机', '好运肯停一停', '总有退路'],
    hint: '同一件事里，较好的分支更常落到你头上。',
    kindBias: 0.4,
  },
  {
    id: 'opening',
    slot: 'means',
    nature: 'possession',
    ranks: ['开局余裕', '带着余温出发', '这一世开得从容'],
    hint: '轮回留下的余粮，让你起步时少一点紧巴。',
    boostDomains: ['career'],
    kindBias: 0.1,
  },
];
