import { ScenarioConfig } from '../core/model';

export const SCENARIOS: ScenarioConfig[] = [
  {
    id: 'childhood',
    title: '童年光阴',
    kind: 'childhood',
    icon: 'seed',
    summary: '还没有道路，只有院子、伙伴和第一次被记住的事。',
    minAge: 0,
    maxAge: 12,
    turns: 3,
    years: 10,
    startResources: { wonder: 2, mischief: 1 },
    resourceLabels: { wonder: '好奇', mischief: '顽皮' },
    modes: ['free'],
    actions: [
      {
        id: 'wander',
        title: '往外跑',
        hint: '好奇增加，也更容易摔一跤',
        icon: 'road',
        outcomes: [{
          id: 'dusty',
          weight: 1,
          text: '你把膝盖跑脏了，却记住了巷子尽头的光。',
          resources: { wonder: 1, mischief: 1 },
          world: { marks: [{ id: 'vitality', intensityDelta: 1 }] },
        }],
      },
      {
        id: 'listen',
        title: '听人讲',
        hint: '把故事听进心里',
        icon: 'book',
        outcomes: [{
          id: 'stories',
          weight: 1,
          text: '大人的话有一半听不懂，你却把另一半留下了。',
          resources: { wonder: 2 },
          world: { marks: [{ id: 'clarity', intensityDelta: 1 }] },
          addTags: ['loves_stories'],
        }],
      },
      {
        id: 'stay_close',
        title: '跟在亲人身边',
        hint: '家里更近，外面少看一点',
        icon: 'home',
        outcomes: [{
          id: 'hearth',
          weight: 1,
          text: '灶火边的位置是固定的。你知道谁会先盛给你。',
          resources: { wonder: 1 },
          world: { relations: [{ id: 'parents', closenessDelta: 1 }] },
        }],
      },
    ],
    beats: [
      {
        id: 'window_ball',
        text: '球又一次偏了。邻居家的窗应声裂开。',
        weight: 3,
        once: true,
        choices: [
          {
            id: 'confess',
            text: '自己去认',
            preview: '短痛，换一句记得',
            outcomes: [{
              id: 'named',
              weight: 1,
              text: '你把零用钱赔完。对方记住的不是窗，是你站在门口的样子。',
              addTags: ['takes_responsibility'],
              world: {
                marks: [{ id: 'presence', intensityDelta: 1 }],
                relations: [{ id: 'neighbor', kind: 'community', label: '邻居', closeness: 4 }],
              },
            }],
          },
          {
            id: 'hide',
            text: '装作没看见',
            preview: '此刻没事，心里有事',
            outcomes: [{
              id: 'kept',
              weight: 1,
              text: '没有人来问。你路过那扇窗时，步子总会快一点。',
              addTags: ['hid_mistake'],
              world: { marks: [{ id: 'isolation', intensityDelta: 1 }] },
            }],
          },
        ],
      },
      {
        id: 'fever_night',
        text: '高烧把一夜拉得很长。有人一直没有离开床边。',
        weight: 2,
        once: true,
        resources: { wonder: -1 },
        world: { marks: [{ id: 'wear', intensityDelta: 1 }] },
      },
      {
        id: 'first_book',
        text: '你发现一本没人借过的书，并把它读到了最后一页。',
        weight: 2,
        once: true,
        resources: { wonder: 1 },
        addTags: ['library_regular'],
      },
    ],
  },
  {
    id: 'studies',
    title: '寒窗',
    kind: 'studies',
    icon: 'book',
    summary: '把日子押在几张纸上。每回选择都会变成考场上的运气。',
    minAge: 10,
    maxAge: 28,
    turns: 4,
    years: 4,
    startResources: { stamina: 3, mastery: 1 },
    resourceLabels: { stamina: '精力', mastery: '功课' },
    actions: [
      {
        id: 'grind',
        title: '再做一卷',
        hint: '功课上涨，精力下降',
        icon: 'book',
        cost: { stamina: 1 },
        outcomes: [{
          id: 'pages',
          weight: 1,
          text: '灯花落了两次。你终于把这卷做完。',
          resources: { mastery: 2, stamina: -1 },
        }],
      },
      {
        id: 'rest',
        title: '先睡一觉',
        hint: '把精力补回来',
        icon: 'lamp',
        outcomes: [{
          id: 'slept',
          weight: 1,
          text: '你没有把坚持等同于不睡。第二天字认得更清。',
          resources: { stamina: 2 },
          world: { marks: [{ id: 'wear', intensityDelta: -1 }] },
        }],
      },
      {
        id: 'ask',
        title: '去问一句',
        hint: '功课小增，也遇见人',
        icon: 'seal',
        outcomes: [{
          id: 'asked',
          weight: 1,
          text: '那人没有直接给答案，却把问题问得更准。',
          resources: { mastery: 1 },
          world: { marks: [{ id: 'clarity', intensityDelta: 1 }] },
        }],
      },
    ],
    beats: [
      {
        id: 'exam_dawn',
        text: '考场的门开了。你必须决定最后这口气用在哪里。',
        weight: 4,
        once: true,
        choices: [
          {
            id: 'all_in',
            text: '把剩下的精力全押进去',
            preview: '功课决定结果，身体会记账',
            outcomes: [
              {
                id: 'passed_hard',
                weight: 2,
                text: '卷面比预想更难，你仍把能抓住的都抓住了。',
                addTags: ['finished_exam', 'exam_focus'],
                world: { marks: [{ id: 'clarity', intensityDelta: 1 }, { id: 'wear', intensityDelta: 1 }] },
              },
              {
                id: 'fell_short',
                weight: 1,
                text: '笔停在最后一题。门外的风比分数更早到来。',
                addTags: ['finished_exam'],
                world: { marks: [{ id: 'wear', intensityDelta: 1 }] },
              },
            ],
          },
          {
            id: 'keep_pulse',
            text: '留一点力气给自己',
            preview: '结果普通，人还在',
            outcomes: [{
              id: 'balanced',
              weight: 1,
              text: '名次不耀眼。你走出考场时，还能看见天色。',
              addTags: ['finished_exam', 'kept_balance'],
              world: { marks: [{ id: 'clarity', intensityDelta: 1 }] },
            }],
          },
        ],
      },
      {
        id: 'friend_calls',
        text: '同窗在窗外喊你。院子里有人正在等。',
        weight: 2,
        resources: { stamina: 1 },
      },
    ],
  },
  {
    id: 'commerce',
    title: '营生',
    kind: 'commerce',
    icon: 'coin',
    summary: '钱会来，也会走。每一回都是一次下注。',
    minAge: 16,
    maxAge: 70,
    turns: 4,
    years: 6,
    startResources: { purse: 3, venture: 0 },
    resourceLabels: { purse: '本钱', venture: '生意' },
    actions: [
      {
        id: 'invest',
        title: '投下本钱',
        hint: '花本钱，换生意或回报',
        icon: 'coin',
        cost: { purse: 1 },
        outcomes: [
          {
            id: 'gain',
            weight: 2,
            text: '货走得比预期快。你第一次听见账房报出盈余。',
            resources: { purse: 2, venture: 1 },
          },
          {
            id: 'loss',
            weight: 1,
            text: '船晚了，货潮了。你把这次当作学费。',
            resources: { venture: 1 },
            world: { marks: [{ id: 'want', intensityDelta: 1 }] },
          },
        ],
      },
      {
        id: 'hold',
        title: '先看一季',
        hint: '稳，少赚',
        icon: 'seal',
        outcomes: [{
          id: 'steady',
          weight: 1,
          text: '你没有追那一波。账本上多的是安全，不是传奇。',
          resources: { purse: 1 },
        }],
      },
      {
        id: 'expand',
        title: '把摊子铺开',
        hint: '需要已有生意',
        icon: 'road',
        cost: { venture: 1 },
        outcomes: [
          {
            id: 'shop',
            weight: 2,
            text: '第二处铺面开门那天，你把自己的名字写上了匾。',
            resources: { purse: 2, venture: 1 },
            addTags: ['has_career', 'built_something'],
            world: { marks: [{ id: 'job', intensity: 2 }, { id: 'means', intensityDelta: 1 }] },
          },
          {
            id: 'thin',
            weight: 1,
            text: '铺开以后，人手和货都不够。你学会了什么叫摊子太大。',
            resources: { purse: -1 },
          },
        ],
      },
    ],
    beats: [
      {
        id: 'boom',
        text: '街上忽然都在买同一种东西。风口就在眼前。',
        weight: 2,
        resources: { venture: 1 },
      },
      {
        id: 'levy',
        text: '税或路费来得比货快。你必须决定要不要硬顶。',
        weight: 2,
        once: true,
        choices: [
          {
            id: 'pay',
            text: '先把这条路买通',
            preview: '本钱减少，生意还在',
            outcomes: [{
              id: 'road_open',
              weight: 1,
              text: '银子少了，车却还能走。',
              world: { marks: [{ id: 'means', intensityDelta: -1 }] },
            }],
          },
          {
            id: 'dodge',
            text: '改道，赌一次',
            preview: '可能省，也可能全无',
            outcomes: [
              {
                id: 'slipped',
                weight: 2,
                text: '你从侧门把货送了出去。心跳比利润更响。',
                world: { marks: [{ id: 'lucky', intensityDelta: 1 }] },
              },
              {
                id: 'caught',
                weight: 1,
                text: '货扣了。你站在空车上，第一次把营生看成天气。',
                world: { marks: [{ id: 'want', intensityDelta: 1 }] },
              },
            ],
          },
        ],
      },
      {
        id: 'partner',
        text: '有人要入股。笑容很干净，合同还没有写完。',
        weight: 2,
      },
    ],
  },
  {
    id: 'craft',
    title: '手上功夫',
    kind: 'craft',
    icon: 'hammer',
    summary: '重复不是停滞。它是把一件事做到能养人。',
    minAge: 14,
    maxAge: 70,
    turns: 3,
    years: 5,
    startResources: { skill: 1, orders: 1 },
    resourceLabels: { skill: '手艺', orders: '活计' },
    actions: [
      {
        id: 'practice',
        title: '再练一遍',
        hint: '手艺上涨',
        icon: 'hammer',
        outcomes: [{
          id: 'repeat',
          weight: 1,
          text: '同一道工序做到第三百次，手比脑子先知道对了。',
          resources: { skill: 2 },
          addTags: ['has_craft'],
          world: { marks: [{ id: 'tools', intensityDelta: 1 }] },
        }],
      },
      {
        id: 'take_order',
        title: '接一单',
        hint: '用活计换口碑',
        icon: 'coin',
        outcomes: [{
          id: 'done',
          weight: 1,
          text: '东西交出去时，对方摸了又摸，才把钱放下。',
          resources: { orders: 1, skill: 1 },
          world: { marks: [{ id: 'means', intensityDelta: 1 }] },
        }],
      },
      {
        id: 'teach',
        title: '把诀窍说给人听',
        hint: '需要手艺已成',
        icon: 'seal',
        outcomes: [{
          id: 'passed',
          weight: 1,
          text: '那人做成的时候，你忽然懂了什么叫留下。',
          addTags: ['passed_on_craft'],
          world: { marks: [{ id: 'presence', intensityDelta: 1 }] },
        }],
      },
    ],
    beats: [
      {
        id: 'master',
        text: '师傅只说：再来。你听出这不是苛刻，是路还没走完。',
        weight: 2,
        resources: { skill: 1 },
      },
    ],
  },
  {
    id: 'journey',
    title: '上路',
    kind: 'journey',
    icon: 'road',
    summary: '把熟悉的街留在身后。路本身会变成经历。',
    minAge: 16,
    maxAge: 80,
    turns: 3,
    years: 4,
    startResources: { stamina: 3, sights: 0 },
    resourceLabels: { stamina: '脚力', sights: '见闻' },
    actions: [
      {
        id: 'go_far',
        title: '再走一程',
        hint: '见闻增加，脚力下降',
        icon: 'road',
        cost: { stamina: 1 },
        outcomes: [{
          id: 'farther',
          weight: 1,
          text: '地名从地图变成了气味、口音和旅店的床。',
          resources: { sights: 2, stamina: -1 },
          addTags: ['left_hometown', 'saw_far_places'],
          world: { setFacts: { residence: 'traveling' } },
        }],
      },
      {
        id: 'linger',
        title: '在这站停一停',
        hint: '恢复脚力，认识人',
        icon: 'home',
        outcomes: [{
          id: 'town',
          weight: 1,
          text: '你在一座小城里住到有人开始用你的名字打招呼。',
          resources: { stamina: 1, sights: 1 },
          world: { marks: [{ id: 'presence', intensityDelta: 1 }] },
        }],
      },
      {
        id: 'return',
        title: '先折回去',
        hint: '结束远行，把见闻带回家',
        icon: 'lamp',
        outcomes: [{
          id: 'back',
          weight: 1,
          text: '家门还在原处。你自己已经不是出门时的尺寸。',
          addTags: ['returned_home'],
          world: { setFacts: { residence: 'hometown' } },
        }],
      },
    ],
    beats: [
      {
        id: 'storm',
        text: '雨把路吃掉了。你必须决定是等还是绕。',
        weight: 2,
        resources: { stamina: -1 },
      },
    ],
  },
  {
    id: 'hearth',
    title: '成家',
    kind: 'hearth',
    icon: 'home',
    summary: '把“我”改成“我们”。责任会来得具体。',
    minAge: 18,
    maxAge: 50,
    turns: 3,
    years: 5,
    startResources: { warmth: 2, strain: 0 },
    resourceLabels: { warmth: '亲近', strain: '牵绊' },
    actions: [
      {
        id: 'stay',
        title: '把时间留给家里',
        hint: '亲近增加',
        icon: 'home',
        outcomes: [{
          id: 'present',
          weight: 1,
          text: '许多第一次你都没有错过。账本涨得慢了。',
          resources: { warmth: 2, strain: 1 },
          addTags: ['made_a_home', 'present_parent'],
          world: {
            setFacts: { partnership: 'home' },
            marks: [{ id: 'presence', intensityDelta: 1 }],
            relations: [{ id: 'partner', kind: 'partner', label: '伴侣', closeness: 6 }],
          },
        }],
      },
      {
        id: 'share',
        title: '把担子摊开',
        hint: '两边都顾一点',
        icon: 'seal',
        outcomes: [{
          id: 'shared',
          weight: 1,
          text: '没有谁独自扛住一切。疲惫里仍有彼此。',
          resources: { warmth: 1, strain: 1 },
          addTags: ['made_a_home', 'shared_parenting'],
        }],
      },
      {
        id: 'keep_room',
        title: '留一点自己的房间',
        hint: '亲近少一点，人还清楚',
        icon: 'lamp',
        outcomes: [{
          id: 'room',
          weight: 1,
          text: '你们没有照着最常见的答案生活，却找到了能呼吸的距离。',
          resources: { warmth: 1 },
          addTags: ['independent_partnership'],
        }],
      },
    ],
    beats: [
      {
        id: 'child',
        text: '家里多了一个很小的人。时间突然不够用了。',
        weight: 3,
        once: true,
        resources: { strain: 1, warmth: 1 },
        addTags: ['raised_child'],
        world: {
          setFacts: { parenting: 'child' },
          relations: [{ id: 'child', kind: 'child', label: '孩子', closeness: 6 }],
        },
      },
    ],
  },
  {
    id: 'service',
    title: '职守',
    kind: 'service',
    icon: 'seal',
    summary: '位置、公文、别人的期限。你在其中找自己的名字。',
    minAge: 18,
    maxAge: 65,
    turns: 3,
    years: 6,
    startResources: { standing: 1, toil: 1 },
    resourceLabels: { standing: '位置', toil: '劳累' },
    actions: [
      {
        id: 'take_hard',
        title: '接下没人要的活',
        hint: '位置上涨，劳累也上涨',
        icon: 'seal',
        outcomes: [{
          id: 'step',
          weight: 1,
          text: '做成以后，有人开始在会上念你的名字。',
          resources: { standing: 2, toil: 1 },
          addTags: ['has_career', 'career_step'],
          world: { marks: [{ id: 'job', intensity: 2 }] },
        }],
      },
      {
        id: 'keep_pace',
        title: '把本分做完',
        hint: '稳',
        icon: 'lamp',
        outcomes: [{
          id: 'duty',
          weight: 1,
          text: '没有升迁。也没有把人做丢。',
          resources: { standing: 1 },
        }],
      },
      {
        id: 'step_back',
        title: '把位置让一让',
        hint: '劳累下降，位置放缓',
        icon: 'home',
        outcomes: [{
          id: 'back',
          weight: 1,
          text: '你第一次把“不必”说出口。肩上轻了。',
          resources: { toil: -1 },
          world: { marks: [{ id: 'wear', intensityDelta: -1 }] },
        }],
      },
    ],
    beats: [
      {
        id: 'layoff',
        text: '部门没了。工牌还在桌上，名字已经不在名单里。',
        weight: 1,
        once: true,
        addTags: ['career_break'],
        world: { setFacts: { occupation: 'searching' }, marks: [{ id: 'job', remove: true }] },
      },
    ],
  },
  {
    id: 'dusk',
    title: '余年',
    kind: 'dusk',
    icon: 'lamp',
    summary: '把走过的路再看一遍。有些话现在才说得清。',
    minAge: 55,
    maxAge: 100,
    turns: 3,
    years: 8,
    startResources: { peace: 2, memory: 1 },
    resourceLabels: { peace: '安稳', memory: '记得' },
    actions: [
      {
        id: 'write',
        title: '把故事写下',
        hint: '记得增加',
        icon: 'book',
        outcomes: [{
          id: 'pages',
          weight: 1,
          text: '许多快要模糊的人重新有了名字。',
          resources: { memory: 2 },
          addTags: ['wrote_memories'],
          world: { marks: [{ id: 'clarity', intensityDelta: 1 }] },
        }],
      },
      {
        id: 'walk',
        title: '去看看还没去的地方',
        hint: '安稳换见闻',
        icon: 'road',
        outcomes: [{
          id: 'late_road',
          weight: 1,
          text: '路比记忆中更远。你庆幸没有再说一次以后。',
          resources: { peace: 1, memory: 1 },
          addTags: ['saw_far_places'],
        }],
      },
      {
        id: 'sit',
        title: '把日子过慢',
        hint: '安稳增加',
        icon: 'lamp',
        outcomes: [{
          id: 'slow',
          weight: 1,
          text: '没有闹钟的清晨起初陌生，后来有了自己的秩序。',
          resources: { peace: 2 },
          addTags: ['retired'],
        }],
      },
    ],
    beats: [
      {
        id: 'child_asks',
        text: '一个孩子问你年轻时是什么样。你讲着讲着，自己也笑了。',
        weight: 2,
        resources: { memory: 1, peace: 1 },
      },
    ],
  },
];
